### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#1]
**Describe the bug**

When I exit out and restart the iOS app it asks me to sign in again. Doesn’t keep me logged in.

**To Reproduce**
Close app - reopen. 

**Expected behavior**

Previously you could leave app and it would keep you logged in when you reopened.

**Screenshots**
N/A

**Desktop (please complete the following information):**
  N/A

**Smartphone (please complete the following information):**
 - Device:  iPhone SE (2nd gen)
 - OS: iOS 16.6
 - Weezify iOS app
 - Version 1.8.6 (153)

**Additional context**
None

**Comment by riverscuomo** [comment]
This will be fixed in 1.8.7 (already available on Android.)

**Comment by riverscuomo** [comment]
Great bug report!

**Comment by KCreek1** [comment]
Confirmed fixed
iPhone SE (2nd gen)
iOS 16.6.1
Weezify 1.8.9 (168)

**Comment by SlightlyCompletely** [comment]
Resolved for iPhone 7 (running iOS 15.7.8) and iPad Air 5th gen (running iPadOS 16.6.1) by updating to Weezify 1.8.9.
