### ISSUE TITLE
Playlist 'play' button always use shuffle mode regardless of what the user has selected

### ISSUE THREAD

**Issue by urbainn** [riverscuomo/public-bug-hunt#102]
**Describe the bug**
When going to any playlist, and clicking the main blue 'play' button, a random track from the playlist will start playing. Even if the user has chosen not to shuffle tracks in the toolbar/controls bar.

**To Reproduce**
1. Go to any playlist
2. Click on the blue 'play' button at the top of the playlist
3. A random track should be playing

**Expected behavior**
I would expect the first track to play, or a random track if shuffle mode is enabled by the user.

**Screenshots**
![Capturevidodu10-01-2024015644-ezgif com-video-to-gif-converter](https://github.com/riverscuomo/public-bug-hunt/assets/47057465/1dee335c-91de-4dd1-be59-ae589b4fb5c7)

**Desktop (please complete the following information):**
 - OS: Linux/Ubuntu
 - Browser: Firefox
 - Version: 1.14.0 (198)

**Comment by KCreek1** [comment]
I missed this yesterday when testing on iOS beta 1.14.0 (198). I was focused on if it would play upon tapping the song. Apologies. 

But this issue is on iOS 1.14.0 (198) as well.

**Comment by urbainn** [comment]
Thanks for the additional info. I just tried on Android 1.13.3 (193) and it works as expected. Version 1.14 may have introduced the bug.

**Comment by KCreek1** [comment]
I think this is working ok on web app now. And since 1.14.0 wasn't deployed to the public on iOS - I think it may be resolved.

**Comment by KCreek1** [comment]
Not an issue in iOS 199 (1.14.0) or 200 (1.14.1)

**Comment by urbainn** [comment]
Not an issue on Android (195) and Web. Closing as completed for now.
