### ISSUE TITLE
Long press on search result causes the screen to go grey

### ISSUE THREAD

**Issue by urbainn** [riverscuomo/public-bug-hunt#103]
**Describe the bug**
In the search results, long-pressing any track will cause the main part of the screen to go grey.

**To Reproduce**
1. Search for any song
2. Long-press on a track
3. Screen should turn grey

**Expected behavior**
I expect long-presses on tracks to have the same effect as clicking on the 'three dots' (add to playlist, etc.), or do nothing.

**Screenshots**

https://github.com/riverscuomo/public-bug-hunt/assets/47057465/761af6b9-72f9-4948-820b-927e49699c51

**Smartphone (please complete the following information):**
 - Device: Sony
 - OS: Android
 - Version [e.g. 22] 194 (1.14.0)

**Comment by Jerrykek** [comment]
https://github.com/riverscuomo/public-bug-hunt/assets/156485289/2ed0b39b-9a9b-490b-88cc-94b8c92f9062

Here is another example. 

• Device: Galaxy Flip 5
• OS: Android 
• Version: [e.g 22] 194 (1.14.0)

**Comment by KCreek1** [comment]
Recreated on iOS as well. 

iPhone SE 2nd gen
iOS 17.2.1
Weezify iOS app 199 (1.14.0)

**Comment by KCreek1** [comment]
In iOS 200 (1.14.1) the issue is rectified.

**Comment by Mel01000001** [comment]
Android build 195 (1.14.1) the issue has been rectified.

**Comment by urbainn** [comment]
I think this issue is resolved, closing for now.
