### ISSUE TITLE
Adding Tracks to Playlist From Track overflow menu

### ISSUE THREAD

**Issue by riverscuomo** [riverscuomo/public-bug-hunt#104]
**To Reproduce**
Playlist > Track		Hit overflow three dots on a track and add to EXISTING playlist
Playlist > Track		Hit overflow three dots on a track and add to a NEW playlist

**Expected behavior**

**Screenshots**
![Screenshot_20240131_065347](https://github.com/riverscuomo/flutter-apps/assets/144285674/c33bf3bf-5b28-4315-9956-040cf1169169)

**Comment by KCreek1** [comment]
I was able to add songs to an existing playlist. However, they would not show on the playlist until I closed and reopened the app. 

iOS 17.3
Weezify iOS 202 (1.14.2)

**Comment by riverscuomo** [comment]
@KCreek1 I'm unable to reproduce this error. are you still seeing it?

**Comment by SlightlyCompletely** [comment]
Issue has reappeared in Weezify 1.17.2 (215) on iPad Air running iPadOS 17.4.1.

**Comment by Mel01000001** [comment]
This happened the first time I added a song in Android build  222 (1.19.0), but after that single occurrence, songs appeared straight away after being added.

**Comment by KCreek1** [comment]
Songs appear right away in v 228 on iPhone.
