### ISSUE TITLE
First Song Not Highlighted in Playlist When Press Play Button

### ISSUE THREAD

**Issue by Mel01000001** [riverscuomo/public-bug-hunt#108]
**Describe the bug**
When the play button is pressed in any playlist, the first song played is not highlighted in blue, but when you skip/go to previous, the songs will be highlighted.

**To Reproduce**
1. Go to any playlist in Your Library.
2. Click on blue play button.
3. Wait for song to play.
4. Song playing will not be highlighted in tracklist.

**Expected behavior**
Song being played should be highlighted in blue.

**Screenshots**

Shows the first song not being highlighted:
https://github.com/riverscuomo/public-bug-hunt/assets/144282154/8b87c048-b0b0-445a-a186-be24a5181c6c

Shows the songs being highlighted when skipping/going to previous:
https://github.com/riverscuomo/public-bug-hunt/assets/144282154/9d230e9c-1c1e-4525-b77f-8480b03605c8

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23+
 - OS: Android v14
 - Weezify Build 219 (1.18.1) - first noticed.  Still an issue in build 222 (1.19.0).

**Comment by KCreek1** [comment]
Just tried on iOS. Same result. 

Weezify ios v 1.19.0 (222)
iPhone SE 2nd Gen
iOS 17.4.1

**Comment by KCreek1** [comment]
Still in v228 iPhone.

**Comment by Mel01000001** [comment]
Still in build 228 Android.

**Comment by riverscuomo** [comment]
@KCreek1 same on a large screen website too?

**Comment by KCreek1** [comment]
I don't know that I noticed on large screen. But I can check in a few minutes and let you know.

**Comment by KCreek1** [comment]
So it seems the issue is only on phone app. 

On large screen web: the first track number turns into a blue icon when you press play.

On iPad app: there are 3 blue dots that appear next to the first track when you press the play button.

**Comment by Mel01000001** [comment]
On large screen web (PC - Chrome): the first track number turns into a blue icon as @KCreek1 mentioned, but the song title is not blue.  I paused the song, then pressed play after which the song title turned blue.

![Screenshot 2024-10-01 113855](https://github.com/user-attachments/assets/5ba66a5d-2b97-45e1-abf4-225e11ccd368)
![Screenshot 2024-10-01 114255](https://github.com/user-attachments/assets/3096b0ca-fbab-4f3b-b60e-08f6082e9537)

**Comment by KCreek1** [comment]
After seeing Mel's comment I went back and tested again. 

For both large screen web app and iPad app: I got the same result as her. Once I paused and restarted then the song title turned blue in addition to the existing blue icon.
