### ISSUE TITLE
Blue Price Button and Demo Bundle Names Missing for Some Demo Bundles in Market

### ISSUE THREAD

**Issue by Mel01000001** [riverscuomo/public-bug-hunt#109]
**Describe the bug**
Blue price button and demo bundle names are missing for Red-Raditude-Hurley, Blue-Pinkerton and Pacific Daydream Black bundles in the Market.

**To Reproduce**
1. Go to Market in account where Red-Raditude-Hurley, Blue-Pinkerton and Pacific Daydream Black bundles have not been purchased.
3. Scroll through available to purchase bundles.
4. Aforementioned demo bundles are missing the blue $9 button and names, eg Alone X: The Red-Raditude-Hurley Years 2006-2010.

**Expected behavior**
Demo bundles to have the blue $9 button and bundle details displayed.

**Screenshots**

https://github.com/riverscuomo/public-bug-hunt/assets/144282154/ab3cf954-6c5c-4c0d-b2dd-308dd4356ce1

![IMG_20240516_054058_2](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/21c6aa5c-4709-4f66-be89-81b97480a960)
![IMG_20240516_054058_1](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/ff26bf45-518f-4eae-b166-ef84f868c003)
![IMG_20240516_054058](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/5ce19f5c-a119-4e82-bf5c-5b9561568204)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S23+
 - OS: Android v14
 - Weezify build 219 (1.18.1) - first noticed.  Still an issue with build 222 (1.19.0).

**Additional context**
Demo bundles can still be purchased by clicking on the bundle images as shown in the video above.

**Comment by KCreek1** [comment]
The same issue is found on iOS. 

Weezify ios v 222 (1.19.0)
iPhone SE 2nd Gen
iOS 17.5.1

**Comment by Mel01000001** [comment]
Fixed in Android build 225 (1.19.1).

**Comment by KCreek1** [comment]
Fixed on iPhone 225 (1.19.1)
