### ISSUE TITLE
New playlists show a duplicate until app closed/reopened

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#112]
**Describe the bug**
When creating a new playlist the playlist shows twice in library until app is closed and reopened. 

**To Reproduce**
1. Click on + in the upper right hand corner of app OR
2. Click on triple dot menu on a song and select add to new playlist
3. Notice on library the new playlist is listed twice
4. Close app and reopen
5. Notice new playlist is only shown once. 

**Expected behavior**
New playlist should only show once in library when it is created. 

**Screenshots**
![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/b8ef4db5-9f86-42be-9c69-83415a6974b9)

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/82905777-c34b-4b58-87da-36ebf9636039)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2nd Gen
 - OS:iOS 17.5.1
 - Version weezify 227 (1.19.3)

**Additional context**
NA

**Comment by Mel01000001** [comment]
Same occurs in Android.

Device: Samsung Galaxy S23+
OS: Android v14
Version weezify 227 (1.19.3)

![Screenshot_20240617_055924](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/4a96df5f-9a75-4bdc-86e9-cdedb0dfcb1b)

**Comment by KCreek1** [comment]
I am not seeing this issue in v 228 on iPhone.

**Comment by SlightlyCompletely** [comment]
This issue no longer appears for playlists I create, but if I add another user’s playlist, that is duplicated.

- iPad Air 5th gen
- iPadOS 17.5.1
- Weezify 228 (1.20.0)

![IMG_5570](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/dca382a6-5223-4aab-839d-90fd0e0b0d5a)
