### ISSUE TITLE
Player bar does not update info w/ first track in playlist

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#118]
If the first track you play is the first track in a playlist - the info in the player bar does not update correctly until you pause and restart.  If you choose any song other than the first one on a playlist as your first track there are no issues.

https://github.com/user-attachments/assets/09eeb6f5-555e-46fe-9d2d-c7204e7065ee

iPhone SE (2nd gen)
iOS: 18.0
weezify v 233 (1.21.2)

also on iPad (7th gen)
ipadOS: 17.7

**Comment by Mel01000001** [comment]
Same on Android.

Samsung Galaxy S23+
Android v14
weezify v 233 (1.21.2)

**Comment by KCreek1** [comment]
Song info now loads correctly in iOS.

**Comment by KCreek1** [comment]
Fixed in android according to comment in discord
