### ISSUE TITLE
Text Cut Off of Bundle Access Confirmation Message After Purchase

### ISSUE THREAD

**Issue by Mel01000001** [riverscuomo/public-bug-hunt#119]
After purchasing a bundle in the Market, the pop up message that states 'You now have access to all the tracks in 'Alone ...' has text cut off the bottom.

Samsung Galaxy S23+
Android v14
weezify v 233 (1.21.2)

https://github.com/user-attachments/assets/156ecda8-39ad-41f7-a17c-7bbb91d378fb

**Comment by KCreek1** [comment]
Full popup shows in iOS.
