### ISSUE TITLE
Cannot reset profile bio

### ISSUE THREAD

**Issue by urbainn** [riverscuomo/public-bug-hunt#12]
**Describe the bug**
Trying to reset your profile bio/remove it will make the app load indefinitely/crash. Upon reloading, the profile bio will be the same as before

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Edit'
3. Remove all text in the 'bio' input
4. Click 'Save'
5. App should load indefinitely

**Expected behavior**
I would have expected the bio to reset (just like when you create a new account), I'm not sure if it's intended to work this way or if you shouldn't be able to reset your bio, but even if it's not, I would expect it to fallback/display an error

**Screenshots**
![dldldlsdlsdlssdfssdfsdfsdfsbgsddeLA PIERRREdddddddLA DEFENSEdmosdfsLA MINEdfdcemo](https://github.com/riverscuomo/public-bug-hunt/assets/47057465/06a94535-92fb-49d0-8720-7685b69abefb)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 116.0.5845.141 (Official build) (64 bits)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia III
 - OS: Android 13

**Additional context**
I was able to reproduce the bug on the web app, and on the Android app (could not try iOS)

**Comment by KCreek1** [comment]
I was able to replicate on iPhone SE (2nd gen) running iOS 16.6 and Weezify 1.8.6 (153). Can change the bio to say something else and it's fine but does not accept blank bio. Just stays in loading screen.

**Comment by SlightlyCompletely** [comment]
Also an issue with Weezify 1.8.6 on iPhone 7 running iOS 15.7.8 and on iPad Air 5th gen running iPadOS 16.6.1.

**Comment by SlightlyCompletely** [comment]
Remains issue on iPhone 7 (running iOS 15.7.9) and iPad Air 5th gen (running iPadOS 16.6.1) in Weezify 1.9.0 (171).

**Comment by SlightlyCompletely** [comment]
Still an issue in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1, but instead of infinite loading screen, pressing “save” just results in my unedited profile remaining on the screen.

**Comment by SlightlyCompletely** [comment]
Resolved in Weezify 1.9.2 (177) on iPad Air running iPadOS 17.0.2.

@urbainn and @KCreek1 Has this issue changed for you?

**Comment by KCreek1** [comment]
The issue remains on iPhone.

**Comment by urbainn** [comment]
Can still recreate issue on Android and Web app too.

**Comment by KCreek1** [comment]
App no longer crashes - it now displays a message: "Bio cannot be empty."

Probably can close this issue.
