### ISSUE TITLE
[web] incorrect dropdown position on playlist right-click

### ISSUE THREAD

**Issue by urbainn** [riverscuomo/public-bug-hunt#16]
**Describe the bug**
On the web app, in the library, right-clicking a playlist opens a dropdown menu, except it is not correctly positioned, in my browser, it's displayed too much on the right.

**To Reproduce**
1. Go to 'Library'/'Your library'
2. Right-click on any playlist
3. Dropdown menu should open, but not where the mouse is

**Expected behavior**
I would have expected the dropdown menu to open where my mouse is currently positioned, or maybe on a fixed point next to the playlist element.

**Screenshots**
If applicable, add screenshots to help explain your problem. These are very helpful!
![dldldlsdlsdlssdfssdfsdfsdfsbgsddeLA PIERRREdddddddLA DEFENSEdmosdWEEZIFYfsLA MINEdfdcemo](https://github.com/riverscuomo/public-bug-hunt/assets/47057465/01000595-3090-4d99-b976-a26e740bf92c)

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version: 116.0.5845.180 (Official build) (64 bits)

**Smartphone (please complete the following information):**
N/A

**Comment by riverscuomo** [comment]
fixed by subtracting 500 from left

```dart
  static showContextMenuForSearchOthersPlaylist(
    BuildContext context,
    Offset offset,
    String playlistId,
  ) async {
    final left = offset.dx - 500;
