### ISSUE TITLE
Audio preview from bundles won’t stop playing when pop-up is dismissed with background tap

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#18]
The audio preview that accompanies a bundle’s pop-up window/overlay won’t stop playing if the screen is tapped outside of the pop-up overlay. The pop-up will close but audio will keep playing until bundle is tapped open again and “Close” on the pop-up is tapped.

1. When logged in to Weezify, go to Profile.
2. Tap on a purchased bundle to open the details overlay. Audio will begin to play.
3. Tap outside of the overlay box to dismiss/close the description overlay.
4. Audio will continue to play despite pop-up overlay being closed.
5. Audio must be stopped by re-opening the bundle’s description and tapping the Close button on the overlay itself.

**Expected behavior**
Audio should stop playing when the overlay is dismissed by tapping the screen outside of it (as well as the option of tapping Close).

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Version: Weezify 1.8.6

**Additional context**
Also occurs on iPhone 7 running iOS 15.7.8.

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/b583b93d-6c8d-4bd8-920f-b9790c8d3324

**Comment by SlightlyCompletely** [comment]
After updating to Weezify v 1.9.0, audio preview no longer occurs when bundle is tapped in Profile. This solves the issue of audio continuing to play but I’m uncertain if there should be audio now or not.

**Device**
 - iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify 1.9.0 (170)

**Comment by SlightlyCompletely** [comment]
Issue exists again in Weezify 1.9.0 (171) on iPad Air 5th gen running iPadOS 16.6.1.

**Comment by SlightlyCompletely** [comment]
Still an issue in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1, but now the audio preview continues to play even after I press “close”. I can try playing other music, but then I just have an audio track playing at the same time as the preview. I have to hard close and restart to stop the audio preview.

**Comment by SlightlyCompletely** [comment]
> After updating to Weezify v 1.9.0, audio preview no longer occurs when bundle is tapped in Profile. This solves the issue of audio continuing to play but I’m uncertain if there should be audio now or not.
> 
> **Device**
> 
> * iPad Air 5th gen
> * OS: iPadOS 16.6.1
> * Weezify 1.9.0 (170)

Update to Weezify 1.9.2 (177) has this result again on iPad Air running iPadOS 17.7.2.

**Comment by KCreek1** [comment]
This occurs on iPhone but is resolved by using the close button on the bottom of the popup. 

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/bdf350ff-608c-473d-aba0-ffc2a26e56d6

**Comment by KCreek1** [comment]
See also issue #76

**Comment by urbainn** [comment]
Also occurs on 1.10.0 (179) on the android app.

**Comment by SlightlyCompletely** [comment]
Issue has worsened in Weezify 1.12.0 (186): dismissing the pop up window by pressing close no longer stops any audio previews playing in the market. (Close does stop audio playing in the profile section.) The audio continues to play if a track is chosen to play and if audio preview starts for another bundle. I had two audio previews and a track playing at once. The audio preview continues even after logging out. It will play until the app is closed completely or the whole audio preview has played.

**Comment by KCreek1** [comment]
The audio preview stops both when you click close and click on the screen outside the box. But the bundle description stays open unless you tap somewhere on the screen off the box. It doesn't close with tapping the close button. 

iPhone SE (2nd gen)
iOS 17.2.1
Weezify ios 188 (1.13.0)

**Comment by KCreek1** [comment]
Fixed in iOS 197(1.14.0)

**Comment by KCreek1** [comment]
This hasn't happened in the last few builds. Going to close.

**Comment by urbainn** [comment]
I can still recreate the issue on Android 1.15.0 (205).
