### ISSUE TITLE
Triple dot menu by song search result leads to white screen

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#19]
Each song search result has a triple dot menu to its right, but when the dot menu is tapped it leads to a white screen.

1. Go to Library.
2. Tap search icon and enter part or whole song title. (Whether or not Search/Enter is pressed when results appear doesn’t matter at this point; the following result occurs in both instances.)
3. Tap the triple dot menu beside a search result.
4. Screen turns white.

**Expected behavior**
The triple dot menu should either lead to further information or not exist.

 - Device: iPhone 7
 - OS: iOS 15.7.8
 - Weezify v 1.8.6

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/e9805da4-6af9-41fa-b213-306f09a815f1

**Comment by urbainn** [comment]
Same issue on Android 13 (61.2.A.0.472) with device Sony Xperia III. Clicking the dots in the search leads to a grey screen.

**Comment by SlightlyCompletely** [comment]
Resolved for me with Weezify v1.8.9 update.

@urbainn Has the Android version been updated? Is this still an issue for you?

**Comment by KCreek1** [comment]
Confirmed fixed 
iPhone SE (2nd gen)
iOS 16.6.1
Weezify 1.8.9 (168)
