### ISSUE TITLE
Switching between apps creates song display issues and eventual app reload

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#2]
**Describe the bug**

When I’m playing a song and I leave the app (say to make a note) and return to the app:  the song continues playing just fine but the player bar defaults back to piano demo. 

**To Reproduce**
1. Open weezify iOS app
2. Select song to play
3. Minimize app and open another
4. Return to weezify

**Expected behavior**
Player control bar should still show correct song. 

**Screenshots**
https://github.com/riverscuomo/public-bug-hunt/assets/144278926/a783323f-2640-489c-b226-ce4b709631fa

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2nd gen)
 - OS: iOS 16.6
 - Browser N/A
 - Version Weezify iOS 1.8.6 (153)

**Additional context**
None

**Comment by Minority103** [comment]
Also, when the song of the playlist picked finishes, piano demos starts playing.       
![photo_6039565875171933580_y](https://github.com/riverscuomo/public-bug-hunt/assets/144348857/89fddadc-0e88-4bd8-b0a0-3ee0501ee2cb). 

 iPhone 14 pro running iOS 16.6 and weezify app 1.8.6 (153).

**Comment by SlightlyCompletely** [comment]
The issue mentioned by the original poster, of current track information reverting to Beethoven while switching apps and thus displaying conflicting info, is also present on iPhone 7 running iOS 15.7.8.

![IMG_8199](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/1bdd9bda-eeff-4eaa-a34a-94d09f2a9553)

**Comment by SlightlyCompletely** [comment]
Issue also occurs on iPad Air 5th gen running iPadOS 16.6.1. Continued app switching, in and out of Weezify and other apps multiple times while music is playing, reveals that the Beethoven track incorrectly displayed as currently playing actually changes to other Beethoven tracks.

Note: The Beethoven track listed at any time does not seem to correlate with number of times switching apps nor with the length of time of the Beethoven track incorrectly displayed.

Repeated app switching also eventually leads to partial screen freezing and spontaneously being logged out/returned to login screen.

Steps to Reproduce:
1. Repeatedly switch in and out of Weezify and various other apps (in regular play mode; not shuffle or repeat).
2. Note that Beethoven track listed in bottom left will change to other Beethoven tracks at times.
3. Continued app switching eventually leads to two frozen screen components in Weezify player: the scrolling current track indicator and the player controls.
4. The Playlist can be scrolled through, so double-tap a different song to play.
5. The currently playing song bar updates to be correct. The player controls begin working properly as well.
6. Switch out of Weezify into another app after a few songs have played.
7. Music stops.
8. Switch back to Weezify. It will be displaying the login screen.


All the above occurred on iPad Air 5th gen running iPadOS 16.6.1 in Weezify 1.8.6.

**Comment by KCreek1** [comment]
Now I am having the entire track list switch to piano, not just the song info on the player control bar. 

1. Select song to play. 
2. Toggle between apps. 
3. Notice piano playlist has replaced correct playlist. 

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/285f2bc5-2ca1-40a7-b909-e914e15ba157


iPhone SE (2nd gen)
iOS 16.6.1
Weezify 1.8.9 (168) public release

**Comment by SlightlyCompletely** [comment]
> Now I am having the entire track list switch to piano, not just the song info on the player control bar.
> 
> 1. Select song to play.
> 2. Toggle between apps.
> 3. Notice piano track list  has replaced correct track list.
> 
>  trim.31F251F1-8CFA-459F-B63A-1E93A554521F.MOV 
> 
> iPhone SE (2nd gen) iOS 16.6.1 Weezify 1.8.9 (168) public release

I also have this issue in Weezify 1.8.9, both in the test and public versions. It happens on both iPhone 7 (running iOS 15.7.8) and on iPad Air 5th gen (running iPadOS 16.6.1).

Also: in the switch from Weezify 1.8.9 beta to public release, the public release now has the currently playing track highlighted in blue (on iPhone 7 running iOS 15.7.8) which did not occur in the test version. This makes it possible to see that the highlighted track *number* is correct in 1.8.9 even though the tracklist contains all sonatas rather than the chosen playlist; for example, when the sixth song (on the chosen playlist) is playing, the sixth sonata track is highlighted in the playlist.

**Comment by SlightlyCompletely** [comment]
Update: I closed my iPad for a few hours, reopened it, and can no longer recreate the sonatas-appearing issue. Now the tracklist stays exactly as it should, even with multiple app switches over multiple songs, in regular play mode (have not tested shuffle nor repeat yet). 

Device: iPad Air 5th gen
OS: iPadOS 16.6.1
Weezify v1.8.9 public release

**Comment by KCreek1** [comment]
I'm still having the issue on both iPhone and iPad. I tried restarting devices and logging out and back in to weezify. 

iPhone SE 2nd gen
iPad 7th gen
iOS 16.6.1
Weezify 1.8.9 public

**Comment by SlightlyCompletely** [comment]
> I'm still having the issue on both iPhone and iPad. I tried restarting devices and logging out and back in to weezify.
> 
> iPhone SE 2nd gen iPad 7th gen iOS 16.6.1 Weezify 1.8.9 public

@KCreek1 Does this happen consistently every time on iPad?

My experience app switching in Weezify v1.8.9 (public) in regular play mode (not shuffle nor repeat) now has me absolutely flummoxed. 

I’ve been getting various bugs in various orders, or sometimes none at all. And I have not been able to replicate any of my experiences even once. Every time I follow the steps I previously used to get a particular bug, I have a slightly different pattern of bugs (or none) appear.

Various events I get when app switching and going back into Weezify:
- the playlist lists all sonatas
- the proper playlist
- the scrolling track title starts or stops scrolling (may be either Beethoven or from the correct playlist)
- the app freezes on the Player screen, sometimes with Market and Profile still being accessible but sometimes not

My process inside the app is always this: 
1. Select a playlist by tapping Player and choosing a playlist from the Library screen. 
2. Double tap the first track in the playlist to start playing. This is where some inconsistency starts: sometimes the track title scrolls and sometimes it doesn’t. 
3. While first song is playing, switch apps. 
3. Switch back to Weezify and somehow get a bug or not. 
4. Continue switching apps. If a bug appeared when switching back to Weezify in step 3, there will usually be a bug with every new switch back into Weezify, but sometimes it corrects itself. 
5. Every switch back into Weezify may contain the same bug as when I previously switched into it or a different one or none. Sometimes one bug will stick around for the entire time I’m listening and switching apps. 

I’ve tried the steps above numerous times from each of the following: 
- a fresh login (from logout, intentional hard close, and a necessary hard close after crash)
- after letting my iPad sleep
- after restarting my iPad
- after a soft close

I’ve done testing sessions where I repeat the process over and over from sleep (or from restart, or from fresh login, etc.) as well as testing sessions by alternating how I enter the app. 

I’ve done test sessions where I just use one playlist and test sessions where I use different playlists. 

I had intended to retest simply to confirm my previous experience or @KCreek1’s, but now I can’t confirm any consistent experience at all. 

Device: iPad Air 5th gen
OS: iPadOS 16.6.1
Weezify v1.8.9 public release

**Comment by KCreek1** [comment]
> @KCreek1 Does this happen consistently every time on iPad?


So I retested this evening on iPhone and iPad. And now I've gotten some playlists to stay and some to get the piano track list to appear. 

I've done these steps:

1.  Select playlist
2.  Select song
3.  Switch app
4.  Return to weezify

My results:  

1.  Everything's fine or...
2.  I see the correct playlist title and the selected song keep playing but the track list and player control bar show piano sonatas.


The pattern that seems to be appearing for me:  the faster I switch to another app, there is an increased chance of the sonatas appearing. So it may be how quickly the playlist is loading on my device over Wi-Fi.

**Comment by SlightlyCompletely** [comment]
When I was focusing on the timing of my app switching earlier today/last night, I didn’t find any correlation with bugs appearing. Your findings encouraged me to try again; still no luck on my end (but it’s been less than an hour of testing this again).

Do you switch apps by minimizing (either the swipe-up-to-dismiss-app or pressing-the-home-button method) and tapping the icon of the app you’re switching to? Or the App switcher method? Or both?

If I could replicate any experience at this point, that would be a start.

Additional information: None of my app switching has been rapid; I move between apps the way I would when not testing. I’ve been switching to Notes, Photos, mail apps, and Safari sites that don’t have video, music, or other visible players which could interfere. The app generally crashes between 30 minutes to an hour into a test, if it crashes.

Device: iPad Air 5th gen
OS: iPadOS 16.6.1
Weezify v1.8.9 public release

**Comment by KCreek1** [comment]
> Do you switch apps by minimizing (either the swipe-up-to-dismiss-app or pressing-the-home-button method) and tapping the icon of the app you’re switching to? Or the App switcher method? Or both?


I usually double tap home button and toggle between open apps. Although I did try tapping home once and minimizing weezify and open another app before returning to weezify. 

2 more things of note:  
1.  I have NOT been able to trigger the piano sonatas to appear for 2 playlists - Liked Songs or Highest rated demos.

2.  I tried downloading the pre- weezer bundle to play offline to see if that avoided the issue. I still was able to trigger the sonatas.

**Comment by SlightlyCompletely** [comment]
> Also of note: I know that previous to this update, while using the player on my phone, it would default back to the piano playlist at right around 1 hour of playtime. I assumed it was due to a timer or screen inactivity. It's the only time before this that I encountered the defaulting to piano playlist.

That brings up one potential difference. On your iPad, have you ever left your iPad alone/had sufficient screen inactivity that your screen shuts off while testing? I’ve never stopped using my iPad long enough for this to happen while testing; I continue using it, so this is finally one possible difference in our testing process (besides the hardware, obviously).

**Comment by KCreek1** [comment]
I have been so focused on the player that I failed to realize it's actually the whole app that reloads when I switch between apps. Probably didn't notice since nothing changes on profile and market when it reloads. So the app seems to be acting like it's reopening when we toggle between apps. 

I downloaded the previous version (1.8.3) for comparison. Definitely did not do that before.

iPhone SE 2nd gen
iPad 5th gen
iOS 16.6.1
Weezify 1.8.6

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/2e8328dc-9878-45e3-a243-9b85b2208d67

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/83655aec-ac62-4e20-ab01-e32be4b9cf9f

**Comment by SlightlyCompletely** [comment]
Further to this issue: 
App switching between Weezify and other apps while in shuffle mode will make Weezify progressively less functional until it freezes and then relaunches.

The app switching during shuffle play can result in different outcomes that are somewhat unpredictable but generally progress in the order below as music playing and app switching continue. This is much like my experience in regular play mode with app switching. Returning to Weezify from another app may:

- display the default sonata playlist, with the current song title scrolling and displaying a sonata;
- display the default sonata playlist, with the current song title displaying a sonata but not scrolling;
- display a screen that is frozen on the default sonata playlist and unresponsive to any tap or scrolling attempts;
- display a mostly blank screen with Profile, Market, and Player icons;
- display the Profile, Market, or Player screens if selected on a previously frozen mostly blank screen before switching out of Weezify;
- display the Profile, Market, or Player screens (if previously selected on the frozen screen mentioned above) but in a frozen/unresponsive state;
- display a fully white screen briefly before the app completely reloads.

Music continues playing in all the above cases except the last, when the screen is fully white and the app reloads.

**Steps to reproduce:**

1. Log out of Weezify and hard close the app. Log in again. (This step is not necessary for the end result but was part of my process for consistency.)
2. In Player, select a playlist from the large library pane.
3. Note that the correct Playlist loads while the scrolling title track is a default Beethoven sonata (as expected).
3. Press Shuffle and then double tap the first track to start playing; OR, double tap the first track, allow track to play for roughly ten seconds, and then press shuffle. Both will give the same result.
4. Note that the double tapped song appears in the scrolling track title area but is no longer scrolling.
5. Allow a few songs to play without switching apps. Note that shuffle seems to work well, though sometimes the current track title scrolls and sometimes it doesn’t. Often it alternates between scrolling or not scrolling with each new track.
6. In roughly the middle of a song, switch out of the app and into another. (Switching in the middle of the song was meant to reduce the possibility of a track in the process of loading to have an influence on the test, though it appears to have no impact on the end result.)
7. Remain in another app while the song finishes and another starts.
8. When the new song is about halfway through, switch back to Weezify.
9. Note that the screen is primarily blank but still has Profile, Market, and Player icons at the bottom. (Photo)
10. Allow the song playing to finish and note that when the next song starts playing, the screen seems to return to normal, except that the playlist is the default sonata playlist and the scrolling title displays a sonata. The music playing will still be the originally chosen playlist. Occasionally switching back to Weezify in step 8 point will not show the blank screen but will show sonatas and the scrolling title as in this step.
11. Switch out of Weezify into another app mid-song.
12. Allow the current song to finish, another to start, and switch back to Weezify mid-song.
13. At this point the screen is usually blank with icons, like step 9, when switching back to Weezify but when the track changes, the list of sonatas is again displayed.
14. When the new track is about halfway through, switch into another app.
15. Switch into a second (non-Weezify) app.
16. When the song changes and the next is roughly halfway through, return to Weezify.
17. Note the mostly blank screen with three bottom icons has returned.
18. Switch out of Weezify to another app before the current track finishes playing.
19. Allow the song to change and play about halfway through.
20. Switch to another app then Back to Weezify. The sonata playlist will be displayed but it will be frozen. No buttons will be responsive and no scrolling is possible.
21. Switch out of Weezify into another app. Whether you do this during the same track or not does not seem to make a difference at all at this point.
22. The music will stop playing after about 30 seconds and does not pick up again.
23. Switch back to Weezify and for about 5 seconds a fully white screen appears without any icons. Then the app reloads and is back at the typical opening screen, displaying the Player and Library of playlists.

Additional notes: 
- Sometimes Weezify will display the sonata playlist for a few songs/switches in and out, and sometimes it will display the mostly blank screen for the duration of a few songs or switches. (Likewise with the frozen playlist screen.)

- Switching between two different apps outside Weezify seems to increase the chance of a frozen or blank screen, but switching between three apps outside Weezify doesn’t seem to have any further impact.

- Pressing Profile, Market, or Player icons on the mostly blank screen will seem to have no effect besides (sometimes) an animation, but when the current track ends and another begins, Weezify will switch to Profile, Market, or Player. Often it will then be frozen as at step 20. Sometimes navigation is possible but the next switch into Weezify is almost always frozen.

- The above tends to in single track repeat mode as well, but will sometimes skip the blank screens and go straight to a frozen playlist like step 20, then follows the same steps from there.

Device: iPad Air 5th gen
OS: iPadOS 16.6.1
Weezify v1.8.9 public release (this also occurred in v1.8.6 and v1.8.9 beta)

Also occurred in these same versions of Weezify on iPhone 7 running iOS 15.7.8.


![IMG_2304](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/3f291124-b61a-4553-a48e-62258c67719a)
![IMG_8223](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/acb52019-f1c2-474a-99ec-0b36282756f8)

**Comment by riverscuomo** [comment]
Still having this issue? I'm not able to reproduce it on 1.9.0.

Select song to play
Minimize app and open another
Return to weezify

**Comment by KCreek1** [comment]
It's still happening for me. But not as consistently. 

Earlier today I was able to let it play for quite some time and toggle between apps with no reload. Then it started happening again. 

I found some playlists rarely reload (for example: liked songs, ewbaite) and others reload every time. 

I've tried letting playlists run longer to see if that helps but it's hit or miss. 

Switching too fast seems to increase the likelihood it happens but it's not a sure thing. 

I really can't see the pattern, if there is one. 

iPhone SE 2nd gen
iOS 16.6.1
Weezify 1.8.9 (168)

**Comment by SlightlyCompletely** [comment]
> Still having this issue? I'm not able to reproduce it on 1.9.0.
> 
> Select song to play Minimize app and open another Return to weezify

@riverscuomo Is this 1.9.0 in Android or is there a beta of 1.9.0 for iOS that hasn’t been pushed out to TestFlight yet?

**Comment by SlightlyCompletely** [comment]
> 
> 
> Earlier today I was able to let it play for quite some time and toggle between apps with no reload. Then it started happening again.
> 
> 
> That doesn't take into consideration that profile and market will also reload sometimes when you toggle between apps. So using the player doesn't seem to be necessary for it to happen. It's just easier to observe because the songs change.
> 

@KCreek1 When you say reload, are you referring to the track titles defaulting back to the sonata playlist? I’m not sure if this is an actual reload or partial reload or not a reload at all. I definitely get the sonata playlist appearing when app switching during music playback (eventually followed by white screens and freezing as I’ve described in comments above) but no visible reload in any section. When you enter Profile or Market while music is playing and then switch apps, do you switch back into Weezify to find them reloading? 

Additionally: when I switch into Weezify from other apps while I’m not playing music, I almost always get a full Weezify reload; this seemed normal to me. It sounds like this may not be the same for you?

My experience has been consistent in Weezify 1.8.6, 1.8.9 beta, and 1.8.9 public release on both my iPad (iPad Air 5th gen running iPadOS 16.6.0 and also in 16.6.1) and on my iPhone 7 (running iOS 15.7.8).

**Comment by KCreek1** [comment]
> @KCreek1 When you say reload, are you referring to the track titles defaulting back to the sonata playlist? I’m not sure if this is an actual reload or partial reload or not a reload at all. I definitely get the sonata playlist appearing when app switching during music playback (eventually followed by white screens and freezing as I’ve described in comments above) but no visible reload in any section. When you enter Profile or Market while music is playing and then switch apps, do you switch back into Weezify to find them reloading? 


When I say reload:

On player:  if I am playing a song and switch between apps then it reloads (blue loading circles) and starts the piano sonatas. Those are the default playlist in weezify. That leads me to conclude it has reloaded to the default setting. 

On profile and market:  since nothing changes on those pages, I have been simply observing the blue loading circles, which tells me it's reloading. 

Since I can't see all the screens simultaneously but have observed them all separately doing the same thing under the same conditions, that's why I'm saying I believe the whole app reloads. 

The last version where this did not occur for me was version 1.8.3. 

I tested this out a couple days ago by loading the older version (1.8.3) and switching between apps. When I did that, no loading circles appeared on profile or market. And they only appeared on player when I deliberately selected a different playlist. Not while switching between apps.

**Comment by SlightlyCompletely** [comment]
Issue also occurs in Weezify 1.9.0 (171) on iPad Air 5th gen running iPadOS 16.6.1.
![IMG_2415](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/72a205e3-dbcc-42eb-8ef7-b6932f62417d)

**Comment by SlightlyCompletely** [comment]
Still an issue in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1.

**Comment by KCreek1** [comment]
It now seems on 1.9.2 (177) the issue is improving.   
As I switch between apps the playlist screen resets to the top but stays on the correct playlist and the correct song is highlighted blue.  The info on the player control bar is the only thing that still changes to sonatas but the correct song keeps playing.  And it's not consistently changing, sometimes it stays on the correct song info.

iPhone SE (2nd gen)
iOS 17.0.2
ios app 1.9.2 (177)

**Comment by SlightlyCompletely** [comment]
> It now seems on 1.9.2 (177) the issue is improving. As I switch between apps the playlist screen resets to the top but stays on the correct playlist and the correct song is highlighted blue. The info on the player control bar is the only thing that still changes to sonatas but the correct song keeps playing. And it's not consistently changing, sometimes it stays on the correct song info.
> 
> 

Also significantly improving in 1.9.2 (177) on iPad Air running iPadOS 17.0.2.

Three issues differ from the iPhone experience quoted above:
1. The current track playing occasionally restarts. This is rare and I haven’t been able to intentionally reproduce.
2. The current track is not highlighted in blue in the playlist (but also never has been, in my experience and as reported here: https://github.com/riverscuomo/public-bug-hunt/issues/34#issue-1890966997)
3. The song title in the control bar always reverts to default sonatas.

**Comment by SlightlyCompletely** [comment]
The issue of getting a white or mostly blank screen when in shuffle mode, as mentioned above, remains in Weezify 1.9.2 (177) on iPad Air running iPadOS 17.0.2.

Steps to Reproduce:
1. Begin playing a playlist in regular play mode.
2. Switch apps occasionally and note that a few of the above mentioned issues still occur (playlist resets to top of screen, no track highlighting, sonatas appear in scrolling title area of player which sometimes scroll and sometimes don’t).
3. While a track is still playing, press shuffle.
4. Continue to switch between apps.
5. After a few switches without any issues beyond the usual mentioned in step 2, note that a switch back into Weezify leads to mostly blank screen.
6. Further switching consistently leads to that same screen. Unlike previous versions, there is no crashing or change to the screen as app switching continues.
![IMG_2587](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/054689df-3c29-4dff-b7b5-310890dd063f)

**Comment by SlightlyCompletely** [comment]
@Minority103 Is this https://github.com/riverscuomo/public-bug-hunt/issues/2#issuecomment-1710140652 still an issue for you? If so, under what conditions does it occur in Weezify 1.9.2 (177)?

**Comment by KCreek1** [comment]
I haven't really had this be an issue in some time. It's possible this may be a closed issue.
