### ISSUE TITLE
Text entered in song search field returns unpredictable results

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#20]
When entering characters in the song search field, it’s impossible to predict how many characters are required to return a desired or accurate search result. For example, “dam” will return “damp” in a song title but won’t return “damage”; “dama” in the search field won’t provide any results; “damag” in the search field will return song titles containing “damage”.

1. Go to the song search field in the library.
2. Enter “dam”, then “dama”, and finally “damag” to see that fewer search characters doesn’t result in a more general (thus larger) pool of search results.

**Expected behavior**
A broader search with fewer characters should return a larger number of results. Additionally, there should be predictability and consistency so that a user doesn’t need to guess how many characters in the search field will result in a successful search. For example, a search for “dam” should return both “damp” and “damage”. A search for “dama” should find “damage”.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.6

This issue also occurs on iPhone 7 running iOS 15.7.8.

![IMG_2280](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/caf771c7-36b5-4ae5-a91e-f6a609a3a58c)
![IMG_2283](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/f87686a4-4787-4f26-be2d-fd8407868dc1)
![IMG_2278](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/07537400-c5e7-4828-b724-02074b89f2f4)

**Comment by SlightlyCompletely** [comment]
Issue remains unchanged and unresolved in Weezify v1.8.9 on both iPhone 7 running iOS 15.7.8 and on iPad Air 5th gen running iPadOS 16.6.1.

**Comment by SlightlyCompletely** [comment]
Still an issue in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1.

**Comment by riverscuomo** [comment]
@SlightlyCompletely still?

**Comment by SlightlyCompletely** [comment]
@riverscuomo Still occurs in Weezify 1.12.0 (186), exactly the same. Tested on iPad Air 5th gen running iPadOS 17.1.1.

**Comment by CTangs** [comment]
Similar/same issue in Weezify Android mobile version 1.17.1

Two track search examples: 

05 King 2 - if you search by "King" it does not show up in results.  If you search only by "Ki" or "Kin" it will appear in results.

Hawaii  9 - if you search by "Hawaii" or even just "Haw" it does not show up in results. If you only use the first two characters "ha" it does. 
![Screenshot_20240411-143914](https://github.com/riverscuomo/public-bug-hunt/assets/65429468/fc73729b-9508-488a-9b8a-3843d94d06f5)
![Screenshot_20240411-144735](https://github.com/riverscuomo/public-bug-hunt/assets/65429468/aa30f7fd-f0ff-4b3c-9a81-b3eb0a9a7d09)
![Screenshot_20240411-144748](https://github.com/riverscuomo/public-bug-hunt/assets/65429468/1b2c9f66-198c-4ce6-8874-5ddc3fde4d9f)
![Screenshot_20240411-143744~3](https://github.com/riverscuomo/public-bug-hunt/assets/65429468/0a7ea743-a338-4fe7-9d07-438a8163b6aa)
![Screenshot_20240411-144812](https://github.com/riverscuomo/public-bug-hunt/assets/65429468/35ca6bbd-9d17-413d-8dd6-aa4a62f97f52)
![Screenshot_20240411-144828](https://github.com/riverscuomo/public-bug-hunt/assets/65429468/e0c1ca23-867c-4141-ab6d-8fda7ecf2a04)
