### ISSUE TITLE
Market Bundle Image size

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#22]
When visiting the Market, bundle images extend past their bounding boxes, over one another, and over bundle prices.

1. Navigate to Market.
2. Bundles visibly overlap.

**Expected behavior**
Bundles should have at least enough space between them for prices to be visible.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.6
 
 
![IMG_2247](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/06ee9ff6-1131-4b4f-99ef-2d10f14b26c2)

**Comment by SlightlyCompletely** [comment]
When enough bundles are purchased, this overlapping issue also appears in Profile. (Still on iPad Air 5th gen running Weezify 1.8.6 on iPadOS 16.6.1.)

![IMG_2292](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/d9eae967-ef71-4437-934a-a1bf764fcff5)

**Comment by Minority103** [comment]
Same on Web app. 
Hp laptop - Chrome.   
![image](https://github.com/riverscuomo/public-bug-hunt/assets/144348857/47a4adb4-4f12-40a2-98d1-64afe537d2a0)

**Comment by SlightlyCompletely** [comment]
Overlap issue has been resolved in Market with the public release version of Weezify 1.8.9, but overlapping still remains in Profile bundles purchased.

Device: iPad Air 5th gen 
OS: iPadOS 16.6.1
Weezify v1.8.9 (168)

**Comment by riverscuomo** [comment]
Now they look too small on a small screen

![image](https://github.com/riverscuomo/public-bug-hunt/assets/24362267/9f5241d9-b04c-49d8-ab8c-9ec858057d87)

**Comment by SlightlyCompletely** [comment]
In Weezify 1.9.0. (171): Overlap issue still resolved in Market but still exists in Profile.

Device: iPad Air 5th gen running iPadOS 16.6.1.

**Comment by SlightlyCompletely** [comment]
Issue resolved for web and in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1.

**Comment by riverscuomo** [comment]
- [ ] small market
- [x] small profile
- [x] large market
- [x] large profile

**Comment by riverscuomo** [comment]
bundle image on small profile and small market are the same but i want the market image to be much larger.

**Comment by SlightlyCompletely** [comment]
Issue occurs once again on iPad with Weezify 1.12.0 (186). Text overflows its box in the market and purchase option is obscured.

Device: iPad Air 5th gen 
OS: iPadOS 17.0.3
Weezify 1.12.0 (186)

![IMG_3276](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/31c1f8f0-2312-4d6e-95e0-5597f06e39f7)

**Comment by KCreek1** [comment]
The images seem to be good on both iPhone and iPad in v193

**Comment by KCreek1** [comment]
Images seem to be good on all screens.
