### ISSUE TITLE
Date and Time headers are not aligned over their respective columns in Player

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#24]
In Player, the Date and Time headers are much further to the right than their respective columns.

1. Go to Player.
2. Select a playlist so that tracks are displayed.
3. Note that Date and Time headers do not align with their respective columns of data.

Date and Time headers must be shifted left so they can properly align with their columns.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.6

![IMG_2272](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/b3031a0f-4ee1-41ac-97a5-e8de57e136ce)

**Comment by Minority103** [comment]
Same issue on webapp. 
HP laptop - Chrome 

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144348857/13ec1e86-0e25-435e-9362-4c4ee8f19141)

**Comment by SlightlyCompletely** [comment]
Still an issue in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1.
