### ISSUE TITLE
Log in grey background cut time and battery icons 

### ISSUE THREAD

**Issue by Minority103** [riverscuomo/public-bug-hunt#25]
The grey background cuts in half all the icons at the top.     

1. Open the app 

**Expected behavior**
For a more estetically pleasant log in screen the icons should be not cut. 

 - Device: iPhone 14 Pro 
 - OS: iOS 16.6 

![photo_6039412841192211250_y](https://github.com/riverscuomo/public-bug-hunt/assets/144348857/9c095f0e-4a83-4326-b841-15038f2107dd)

**Comment by riverscuomo** [comment]
like this?

![image](https://github.com/riverscuomo/public-bug-hunt/assets/24362267/5967c263-67a3-4152-9166-120acfaab9e6)

**Comment by Minority103** [comment]
Yes, that's perfect.

**Comment by taylorlee3** [comment]
@Minority103 is this still happening to you?

**Comment by Minority103** [comment]
No, now it's perfect!

**Comment by SlightlyCompletely** [comment]
Looks great/resolved on iPhone 15 Pro running iOS 17.1.2 in Weezify 1.13.0 (188). Closing as resolved.
