### ISSUE TITLE
Delete account button does not delete account

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#26]
After pressing the “Delete Account” button, the main pane of Weezify displays the login screen as if I have logged out, but the library remains on the left and the player at the bottom. I can click Profile, see my purchased bundles, and still play them. By many further attempts to “activate” the delete, as listed below, I only managed to make all playlists appear.

1. Go to Profile.
2. Tap “Delete Account”.
3. Login window displays in main window. But bottom menu, player controls, and library are still completely accessible. (Photo A)
4. Go to Profile. Purchased bundles can still be seen. (Photo B)
5. Go to Player. All playlists are visible and purchases can still be played.

 I wanted to see if I could solve this by logging out, so that’s what I attempted next.

6. Go to Profile and Log out.
7. Standard Login window appears.
8. Enter the username and password of the account that was supposedly just deleted.
9. The box asking for a username pops up. (Photo C)
10. Enter different username from what was used before.
11. Screen now displays just New Releases and Like Songs playlists.
12. Go to Profile.
13. Previously purchased bundles are still there.
14. Go to Market.
15. Click on a bundle that was previously purchased.
16. A message appears saying the bundle was already purchased but can be gotten again for free. (Photo D)
17. Choose to get again for free.
18. Go to Profile and bundle appears twice.
19. Still only the New Releases and Liked Songs playlists are displayed.
20. Go to Profile.
21. Press on a purchased bundle to display the bundle preview information.
22. Navigate to Player and bundle preview audio continues to play.
23. Go back to Profile and tap the purchased bundle whose audio is playing.
24. When the bundle preview pop-up window opens, tap Close.
25. Audio continues to play.
26. Try to log out from Profile.
27. Audio continues to play even when supposedly logged out and standard login window appears. (Video)
28. Hard close.
29. Logging back into account shows expected screens at this point: just the two playlists again, and purchased bundle is still visible in Profile (though now just displayed once).
30. Log out.
31. Log in with another account then log out.
32. Log in to account that refuses to delete.
33. It loads and displays all playlists. Attempt to delete has thus provided more access.
34. Go back to Profile and press Delete Account again.
35. This returns to the screen shown in Photo A/Step 3 above.

**Expected behavior**
Account should delete and all data should be erased. Login window should appear.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.6

**Additional context**
Just prior to logging into the account I wanted to delete, I attempted to log into the account on my iPhone 7 running iOS 15.7.8 in Weezify 1.8.6.
Instead of being able to log in, I got an error message stating that there was no user data corresponding to my login info and the user may have been deleted. (Photo E) I had not deleted anything at that point but it inspired me to try deleting the account if I could manage to log in on my iPad. Somehow the iPad login did work, as all steps above show.

Photo A
![IMG_2305](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/3e426aa5-f497-4ebe-bd37-5721a49b1252)

Photo B
![IMG_2306](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/24f2aa97-f2b1-4d86-9841-100fd6971c4a)

Photo C
![IMG_2307](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/0afa05ce-d672-47a2-bab8-74f69f4d6822)

Photo D
![IMG_2308](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/4fefc82b-2388-4680-84c1-027a6f96d657)

Video

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/fe939dfe-fb80-4fa7-9386-3f667b5834cb

Photo E
![IMG_8210](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/76b60b1c-d532-420c-a28f-18ada2c6d99f)

**Comment by riverscuomo** [comment]
@SlightlyCompletely I thought you were on Weezify v1.8.3?

**Comment by SlightlyCompletely** [comment]
@riverscuomo Ah, I must have misunderstood your earlier question. I thought you were asking about current public as opposed to test versions. All my testing has been v1.8.6 since I got access to it, so everything on GitHub is 1.8.6.

**Comment by riverscuomo** [comment]
ah, ok. I forgot which version was in ios beta.

**Comment by SlightlyCompletely** [comment]
Based on your comment in TestFlight, it now occurs to me that maybe iOS group has been testing 1.8.7 for the past few days instead of 1.8.6; I’m not sure if your note there meant that the current version has a corrected build number from a previous version or if the current version didn’t get incremented.

But just clarify, because I see I’ve accidentally left it out of some comments here (still getting the hang of this), I’m definitely on the most recent beta. I’ve been labelling it as 1.8.6 since that’s what it says in the app and iOS folks here have at least been consistent on that, even if we’re all wrong.

**Comment by SlightlyCompletely** [comment]
I’ve managed to get Delete Account to partly work on my iPhone 7, but not in the way it should. Instead it draws from solutions in Issue 13 (specifically logging out, logging into then out of another account, then logging back into the deleted account with the same email address and password that were originally used). This means that my email address and password are still registered, verified, and/or linked to one another. Also an account is only deleted by reusing it as a new account.

Steps to reproduce:
1. Navigate to Profile.
2. Select Delete Account.
3. Message that account was deleted will appear for a few seconds then fade.
4. The Player bar will still be present and bundles purchased can still be played.
5. Navigate to Profile and the account name shows the name and purchases of the account that was supposedly deleted.
6. When in Profile on Weezify, switch out of the app into another, then back into Weezify.
7. Profile page now says Lurker. (Photo A)
8. Navigate to Market and note that previously purchased bundles are still associated with the account. (Photo B)
9. Navigate to Player and note that purchased bundles can still be played.
10. Log out of account.
11. Log into and out of another account.
12. Log back into Weezify with account you tried to delete.
13. Screen appears asking you to select a username.
14. Enter a username and app loads into a new account.
15. Navigate to Profile. Note that there are no purchased bundles listed here now.
16. Previous account was deleted only by using it again as a new account, and only after logging out, using another account, and logging back in. 

Account deletion should clear all saved data so that email address and password from a deleted account can no longer be used to log into the “deleted” account, nor or they still associated with each other. Account deletion should also take user to a screen that contains only the login window so that the player and library cannot be used to navigate back into the account.

Device: iPhone 7
OS: iOS 15.7.8
Weezify v1.8.6


Photo A:
![IMG_8213](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/6fab9368-414a-48f3-be4d-b9bdd7ad14f4)

Photo B:
![IMG_8214](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/0b02a7c3-2d14-45cd-acf6-0d0235d315ac)

**Comment by SlightlyCompletely** [comment]
Issue resolved in public release of Weezify 1.8.9.

Resolved for both iPad Air 5th gen (iPadOS 16.6.1) and iPhone 7 (iOS 15.7.8).
