### ISSUE TITLE
Attempting to purchase first bundle in brand-new account returns message that I already own it

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#28]
In any brand-new account I set up now, my first attempt to purchase a bundle in that account gives me the message that I already own the bundle, but would I like to get it again for free. These are accounts that I’ve opened minutes before and have never made purchases in.

I suspect this is related to some sort of cache issue; to test and try to resolve other bugs, I’ve “purchased” most bundles in other accounts. Even though I’ve used 7 different email addresses on 3 domains and 2 devices, it seems that Weezify thinks, when I try to purchase a bundle in the Market, that even my new accounts already own the bundles. 

In my most recent experience in trying to purchase a bundle in a new account, Weezify appears to have switched from being in the Market to my Profile during the purchase attempt.

1. Purchase all or most bundles using various accounts.
2. Log out.
3. Create new account from Login screen.
4. Immediately verify address, sign in, and create username.
5. Check Profile and observe that no bundles are owned.
6. Go to Market and tap a bundle that you own in a different account.
7. Proceed to try to purchase bundle.
8. Note that a message appears saying you already own that bundle.

**Expected behavior**
A brand-new account would not own any bundles, so should not get a message that a bundle is already owned and can be acquired free.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.6

**Additional context**
Issue also occurs in Weezify v1.8.6 on iPhone 7 running iOS 15.7.8.

![IMG_2314](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/3c00778a-7be0-4f89-9516-798d74320aca)

![IMG_2308](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/91bad452-e22c-426c-9594-929069aad960)

![IMG_8211](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/52f64911-ffe8-4ac7-969a-62c150dc9df2)

**Comment by KCreek1** [comment]
Is it possible this is triggered by the payment method being through Apple ID?  Even though the email addresses and accounts for Weezify are different - I wonder if as it's processing the "payment" through Apple it's recalling the previous sale and preventing what it views as a double charge.

**Comment by SlightlyCompletely** [comment]
Very good point. It does indeed look more like an Apple system message, since the app’s messages appear more in this style:
![IMG_2302](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/251f4d52-5fc1-4311-9ce4-35349b3d928f)

**Comment by SlightlyCompletely** [comment]
Would this help at all? https://stackoverflow.com/questions/2474663/how-to-skip-the-alert-youve-already-purchased-this-but-it-hasnt-been-download

**Comment by riverscuomo** [comment]
Yeah that message isn't coming from me.

**Comment by SlightlyCompletely** [comment]
So this technically isn’t a bug in the app, but a bug in Apple’s test environment.

**Comment by SlightlyCompletely** [comment]
Even if this is a bug in Apple’s test environment, it seems to be affecting how the app recognizes purchases:

If I click Restore Purchases in Market, the app gives me the message “Your purchases have been restored.” That message lists all purchases not just from that account but from all accounts I’ve used in testing. I can click Restore Purchases even if the account I’m using hasn’t made any purchases.

I go into detail here:
https://github.com/riverscuomo/public-bug-hunt/issues/29#issue-1888812714

The issues seem to be related, but issue 29 was tested in accounts that weren’t new, and the restored purchases message doesn’t appear to be in the standard Apple alert style.

**Comment by KCreek1** [comment]
Message has not appeared in quite sometime. Closing issue.
