### ISSUE TITLE
Liked Songs playlist - grey screen

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#3]
**Describe the bug**
Liked Songs Playlist displays grey screen. 

**To Reproduce**
1. Log in to Weezify iOS app.
2. Select Liked Songs Playlist.
3. Grey screen appears.  

**Expected behavior**
Should display list of songs you have rated in Weezify. 

**Screenshots**
![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/612e3eab-e11f-4b07-8f11-9b0b817d0297)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2nd gen)
 - OS: iOS 16.6
 - Version Weezify iOS app 1.8.6 (153)

**Additional context**
None

**Comment by KCreek1** [comment]
This is also an issue for new releases playlist. Grey screen when selected.

**Comment by KCreek1** [comment]
Confirmed fixed 
iPhone SE (2nd gen)
iOS 16.6.1
Weezify 1.8.9 (168)

**Comment by SlightlyCompletely** [comment]
No more grey screen; issue is fixed for iPad Air 5th gen (running iPadOS 16.6.1) and iPhone 7 (running iOS 15.7.8) by updating to Weezify 1.8.9.

**Comment by Minority103** [comment]
Working iPhone 14, closing the issue.
