### ISSUE TITLE
Highest Rated Demos playlist displays only to Lurkers (not for users logged in)

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#30]
When a user is not logged in to Weezify, the Highest Rated Demos playlist appears. Trying to play this list will prompt the Lurker to purchase it in the Market. The Highest Rated Demos playlist does not display for registered, logged in users.

1. Log into Weezify account.
2. Observe playlists and the absence of Highest Rated Demos. (When account is loading, Highest Rated Demos playlist may appear briefly among playlists then disappear. It did not in my first experience but did when I retested the process.)
3. Navigate to Profile and log out of account.
4. When login screen appears choose maybe later.
5. Allow Weezify to load and navigate to Profile to confirm Lurker mode.
6. Navigate to Player. Playlist will be visible both there and in lefthand menu.

**Expected behavior**
The Highest Rated Demos playlist should display for users who are logged in.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.9

Issue also occurs in Weezify 1.8.9 on iPhone 7 running iOS 15.7.8.

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/c983d36a-a32a-481c-aa84-46d3407a847f

**Comment by KCreek1** [comment]
Interesting - the highest rated demos playlist still shows on my actual weezify account that I had before entering TestFlight. But does not show on any of the ones I created in TestFlight. 

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/59fb0ab8-321a-4950-bbe1-b904ba00ff8b)

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/0d44b9d2-dd28-46d4-b32e-93d64478bae5)

iPhone SE (2nd gen)
iOS 16.6.1
Weezify 1.8.9 (168)

**Comment by SlightlyCompletely** [comment]
@KCreek1 Do you also find that you can access the Highest Rated Demos when logged out of Weezify (viewing as a Lurker)?

**Comment by KCreek1** [comment]
@SlightlyCompletely yes. I can access the list. They don't play because they're not purchased. But I see them.

**Comment by SlightlyCompletely** [comment]
Issue remains in Weezify 1.9.0 (171) on iPad Air 5th gen (iPadOS 16.6.1).

**Comment by SlightlyCompletely** [comment]
Issue remains in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1.

**Comment by KCreek1** [comment]
I can now see this playlist on new accounts. 

iPhone SE 2nd gen
iOS 17.0.3
Weezify v 186 (1.12.0)

**Comment by SlightlyCompletely** [comment]
Still an issue for me in Weezify 1.12.0 (186) on iPad Air 5th gen running iPadOS 17.0.3.

**Comment by KCreek1** [comment]
I see this playlist both on iPhone and iPad.
