### ISSUE TITLE
iPad version of Weezify intermittently displays tracks in New Releases playlist

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#31]
When using Weezify 1.8.9 on iPad, selecting the New Releases playlist from the library opens the playlist but no tracks listed. After switching to another app then back to Weezify, tracks appear. They appear to be all the Bach/Beethoven tracks. Navigating to Profile, Library, or Market and then back to the New Releases playlist will again display the playlist without any tracks. It seems possible to continue app switching to bring back the track list.

1. Log in to Weezify on iPad.
2. Navigate to Library.
3. Select New Releases playlist.
4. When it opens, no tracks are listed.
5. Switch to another app then back to Weezify.
6. Tracks will be listed. They will be sonatas from the Beethoven/Bach playlist.
7. Navigate to Profile, Library, or Market.
8. Navigate back to New Releases playlist.
9. No tracklist will be displayed.
10. Switching to another app then back to Weezify will again show a tracklist for the New Releases playlist.

**Expected behavior**
The New Release playlist should either display nothing, if there are no new releases, or it should consistently display a tracklist whether switching apps or switching through Profile, Library, or Market and back to the playlist.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.9

![IMG_2331](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/7e83cc51-4296-4384-ad0b-295327f9d5ba)
![IMG_2330](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/8a57540b-2a12-40e2-992d-e21a067c335c)

**Comment by KCreek1** [comment]
I show 2 songs in new releases on iPhone today. So it seems it's not limited to iPad. They seem to be the ones that are referencing in the new playlists issue. 

iPhone SE 2nd gen
iOS 17.0.3
Weezify iOS app 1.10.0 (179)

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/e25d5258-d252-45e9-a47b-2fad0c071762)

**Comment by KCreek1** [comment]
I think this is connected to issue #2 - same thing happens, switching leads to piano demos appearing.

**Comment by SlightlyCompletely** [comment]
Resolved for iPad Air 5th gen running iPadOS 17.0.3, with update to Weezify 1.12.0 (186).
