### ISSUE TITLE
Large screen Weezify is missing New Releases and Liked Songs playlists from lefthand menu

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#32]
In Weezify 1.8.9 on iPad, the lefthand menu doesn’t display New Releases or Liked Songs playlists. They can still be found in the library.

1. Log in to Weezify on iPad.
2. Note that New Releases and Liked Songs playlists are missing from lefthand menu.
3. Navigate to Library.
4. New Releases and Liked Songs playlists are visible and accessible.

**Expected behavior**
The Liked Songs and New Releases playlists should be displayed in the lefthand menu, not just in the library.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.9
![IMG_2328](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/bfe2d32c-1ee8-4a2c-8841-b980b701ea6a)

**Comment by SlightlyCompletely** [comment]
Issue remains in Weezify 1.9.0 (170) on iPad Air 5th gen running iPadOS 16.6.1.

![IMG_2404](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/5c2e814c-8b14-45ed-94f8-5ee1bdc414cc)

**Comment by SlightlyCompletely** [comment]
Issue remains in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1.

**Comment by KCreek1** [comment]
This is also true in desktop browser - both of these playlists is missing.

Windows
Chrome
web app 1.9.2 (176)

**Comment by KCreek1** [comment]
I see both of these playlist in library on large screen now.
