### ISSUE TITLE
Just the first song is highlighted on searchbar while playing 

### ISSUE THREAD

**Issue by Minority103** [riverscuomo/public-bug-hunt#33]
When playing songs on searchbar results, just the first song is highlighted even if listening to the ones below. 

1. Go to 'Search bar'
2. Write 'Pacific'
3. Select the second song 

**Expected behavior**
The song selected become blue. 

![photo_6046617391133212106_y](https://github.com/riverscuomo/public-bug-hunt/assets/144348857/512b05eb-edf8-4a56-9c6b-7b552e441ffa)

 - Device: iPhone 14 Pro 
 - OS: iOS 16.6

**Comment by KCreek1** [comment]
This seems to be fixed in iOS 200 (1.14.1)
