### ISSUE TITLE
Blue highlighting missing on bottom screen icons and currently playing track on playlist

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#34]
Profile, Market, and Player icons all animate when tapped but only the Player icon has the blue highlight (and it remains blue all the time). Similarly, the playlist does not highlight the current track in blue.

Steps to reproduce the behavior in playlist:
1. Choose any Playlist. Double tap a song to start playing.
2. The tapped track will have a gray background to show it’s selected, but will not highlight in blue.
3. Allow the music to continue and note that the next song also has no blue highlight to indicate it’s playing.

Steps to reproduce the behavior in icons:
1. Note that Player icon is highlighted blue when app opens.
2. Tap Profile and note there’s an animation but the icon doesn’t highlight in blue when on Profile screen.
3. Tap Market and note animation is present but no highlight, similar to Profile.
4. Tap Player and note that it has an animation, as well as staying blue the whole time the app is open.

**Expected behavior**
The Player, Market, and Profile icons should highlight blue to indicate which screen you’re on. The current track in the playlist should be highlighted blue to indicate which track is playing.

 - Device: iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.9 public release

**Additional context**
This highlighting issue does not occur on iPhone 7 (running iOS 15.7.8 and the public release of Weezify 1.8.9).

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/63c146c8-99a6-408a-9600-7cb769ec3992

![IMG_2358](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/0319c0c9-667a-41ae-a12e-f20422dc2dfa)

**Comment by riverscuomo** [comment]
We can leave this issue as is for now, but in the future I would file bugs like this as two separate issues.

**Comment by KCreek1** [comment]
The current track now highlights in blue as the songs play in latest version. The only thing remaining on this issue is the highlighting on the bottom between market, search, and player to indicate which screen you're on. 

 Will updating title to reflect that.
