### ISSUE TITLE
Playlists with songs not owned crashing app/freezing player

### ISSUE THREAD

**Issue by urbainn** [riverscuomo/public-bug-hunt#35]
**Describe the bug**
When listening to a playlist that contains tracks from bundles you don't own:
- Skipping from an owned song to one that you don't own will freeze the player. You have to press the skip button manually in order to play the next song. If there are multiple songs you don't own back to back, then you will have to press the skip button n times.
- When a song ends, then if the next track is from a bundle you don't own, it will crash the app (display a grey screen in the main display), you cannot get rid of the grey screen unless reloading the app.

**To Reproduce**
1. Go to a playlist containing songs from a bundle you do not have ('Highest Rated Demos' is where this happens the most for me)
2. Press the play button (or play any song)
3. Skip until you come across a song from a bundle you don't have => player freeze
3. Let a song end by itself, with the next track being from a bundle you have not purchased => app crash

**Expected behavior**
I would expect the track to be automatically skipped when not owned.

**Screenshots**
Video:
https://github.com/riverscuomo/public-bug-hunt/assets/47057465/65292253-b25c-4b03-a471-ffff1b82b29e

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version: 116.0.5845.180 (Official build) (64 bits)

**Additional context**
Could not recreate on Android.

**Comment by KCreek1** [comment]
I think this is working correctly now.
