### ISSUE TITLE
Search bar does not appear when click on search

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#38]
**Describe the bug**
When you click on "search" on the web app - nothing happens. 

**To Reproduce**
1.  Open Weezify in browser
2.  Select "search" from upper left hand menu
3.  No search bar or other option to enter your search appears

**Expected behavior**
Clicking "search" should give user an option to enter character to search. 

**Screenshots**
https://github.com/riverscuomo/public-bug-hunt/assets/144278926/d3af0d2d-85a6-42c1-8961-b46ce2e725c8

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome v 117.0.5938.64
 - Version web app 1.9.0 (170)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2nd gen
 - OS: iOS 16.6.1
 - Browser Safari
 - Version web app 1.9.0 (170)

**Additional context**
On small screen - the left menu is not visible unless you rotate device horizontally. 

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/338aae20-2958-4dea-b5cd-64f148df2315

**Comment by gabbysjohnson** [comment]
Still not working after 1.9.0 update.

**Comment by KCreek1** [comment]
Still an issue on iOS 1.9.0 (170)

**Comment by SlightlyCompletely** [comment]
Issue also occurs on iPad Air 5th gen. Animation for pressing search appears along with a blank screen but no search box.
OS: iPadOS 16.6.1
Weezify v1.9.0 (170)

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/806122b5-719a-470b-9b5f-994090ee180b

**Comment by KCreek1** [comment]
Still an issue with 1.9.0 (171)

**Comment by KCreek1** [comment]
Got the search bar working - using bottom menu. 

iPhone SE 2nd gen
iOS 16.6.1
Weezify iOS app 1.9.0 (171)

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/6c12c308-2427-4f35-aaf9-308692182d7e

**Comment by KCreek1** [comment]
Search bar now working on small screen web app iPhone and iPad. Web app v1.9.0 (173)

**Comment by Mel01000001** [comment]
On Android, when clicking on search button, nothing happens.

![Screenshot_20230923_215923](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/8b8e9015-6768-48f0-b7ee-7e35d99abc08)


Search bar appears when clicking on search at bottom of screen.

![Screenshot_20230923_215955](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/e9dd3da0-3d74-4e48-a44d-46f33758a9b9)

**Comment by KCreek1** [comment]
Both top and bottom search buttons working in iOS app 1.9.0 (174).

iPhone SE (2nd gen)
iOS 17.0.1
Weezify iOS app 1.9.0 (174)

**Comment by SlightlyCompletely** [comment]
Issue exists in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1 when tapping magnifying glass at top of page. Page not found error appears. Search option on left does work.


https://github.com/riverscuomo/public-bug-hunt/assets/144279871/a2c09294-4ec7-4f4c-819c-68f485ebbfba

**Comment by SlightlyCompletely** [comment]
Issue remains in Weezify 1.9.2 (176) on iPad Air running iPadOS 17.0.1; tapping the search icon at the top of the app leads to “page not found” message.

![IMG_2518](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/93e032ab-310d-4ff0-b2d2-2fa0e8e86a48)

**Comment by KCreek1** [comment]
After looking at web app on my desktop - when I let my mouse hover over the magnifying glass found in profile - it says "search neighbors" - when I click on it, I receive the exception that is posted above.  So I am wondering if on iPad and iPad web if it serves that function as well.  Which would leave the search for songs, playlists, and artists as the button on the left.

**Comment by KCreek1** [comment]
Given all platforms have song, playlist, and artist search available. Will close this issue with the note that "neighbor search" button found in profile on iPad app and iPad web is noted in another issue.
