### ISSUE TITLE
Track repeat has no audio when repeat is chosen before music is played

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#39]
**The bug:**
If repeat is double-tapped (to enter single track repeat mode) before a track is chosen to play, there is no audio when playing.

**To Reproduce:**
1. Choose a playlist from the library.
2. When it loads in Player, double tap repeat to enter single track repeat mode.
3. Double tap a track to start playback.
4. Note that the player controls indicate the track has started and is playing, but there is no audio.

**Expected behavior:**
Following steps 1-3 above should lead to song playback with audio.

**Additional information:**
- If you “listen” to part of the track without audio and then double-tap another track to play/test, that track will also fail to have audio.
- When double-tapping the repeat button *after* a track has started playing, this issue does not occur.
- The issue can be resolved by pressing pause and the play again in the Player controls. This results in the song being refreshed and starting from its beginning.

**Device:** iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.8.9 public release

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/dc9863ba-8824-4055-8d31-1702544c8a29

**Comment by riverscuomo** [comment]
I can't reproduce this on Android 1.9.0

**Comment by KCreek1** [comment]
I was just able to reproduce on iPhone SE 2nd gen.

**Comment by SlightlyCompletely** [comment]
Issue also occurs in Weezify v1.9.0 (170) on iPad Air 5th gen (running iPadOS 16.6.1) and on iPhone 7 (running iOS 15.7.9).

**Comment by KCreek1** [comment]
Seems to be fixed in 1.9.0 (171)

**Comment by SlightlyCompletely** [comment]
Still occurs on iPad Air 5th gen (iPadOS 16.6.1) in Weezify 1.9.0 (171).

**Comment by SlightlyCompletely** [comment]
Also still occurring on iPad Air running iPadOS 17.0.1.

**Comment by SlightlyCompletely** [comment]
Issue remains in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1.

**Comment by KCreek1** [comment]
Resolved on iPad 7th gen running weezify 188 (1.13.0)
