### ISSUE TITLE
Small Appbar missing Circle Avatar, good evening, and create playlists button

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#41]
**Describe the bug**
There is no way to get to the profile screen. Prohibits signing out/switching accounts. Or if a lurker - being able to make account. 

**To Reproduce**
1. Open app
2. Only market, search, and your library are available. 
3. No option for profile. 
4. Tried clicking on pfp in market but nothing happened. 

**Expected behavior**
Should have access to profile page.

**Screenshots**
https://github.com/riverscuomo/public-bug-hunt/assets/144278926/a4dafe83-7b7b-45ef-a54f-e763026e1ee9

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
- iPhone SE 2nd gen
- iOS 16.6.1
- weezify ios 1.9.0 (170)

**Additional context**
None

**Comment by riverscuomo** [comment]
can you tap on your avatar top right?

**Comment by riverscuomo** [comment]
![image](https://github.com/riverscuomo/public-bug-hunt/assets/24362267/3be1dc18-fc81-4fd9-9bc0-4f7ab464cc1a)

**Comment by KCreek1** [comment]
The only thing I show top right is the search. Is it supposed to be to the right of that?  If so, I don't see it. 
![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/996509fa-21bc-4489-a155-528bedf102b3)

**Comment by SlightlyCompletely** [comment]
Also no avatar on iPhone 7 (running iOS 15.7.9) in Weezify v1.9.0 (170).

**Comment by KCreek1** [comment]
I tried rotating my phone. Then it formats like an iPad and I can see the profile. If I click on it then rotate back to portrait view - my profile is there.

 https://github.com/riverscuomo/public-bug-hunt/assets/144278926/62304a3d-c488-4a98-8fa8-2c515235675a

**Comment by SlightlyCompletely** [comment]
Even in landscape orientation, my iPhone fails to show the avatar.

Device: iPhone 7
OS: iOS 15.7.9
Weezify v1.9.0

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/314ba44a-df97-4386-bfe4-f943fb35c681

**Comment by riverscuomo** [comment]
problem is here 
either no user
or currentroute doesn't contain "/"

```dart
/// The appbar for the small screen on both Weezify and Rivify
class SmallAppBar extends StatelessWidget {
  const SmallAppBar({
    super.key,
    required this.profileImageUrl,
    this.toolTipText = 'Search your library',
    required this.isAnonymous,
    required this.playerBloc,
    this.user,
    required this.currentRoute,
  });

  final String profileImageUrl;
  final String toolTipText;
  final bool isAnonymous;
  final BasePlayerBloc playerBloc;
  final User? user;
  final String currentRoute;

  @override
  Widget build(BuildContext context) {
    final _onHomeScreen = currentRoute.contains('"/"');
    final _onPlayerSearchScreen = currentRoute.contains('playerSearch');
    return AppBar(
      backgroundColor: const Color.fromRGBO(18, 18, 18, 1),
      title: Row(
        children: [
          if (user != null && _onHomeScreen)

**Comment by KCreek1** [comment]
All show at the top. 

iPhone SE 2nd gen
iOS 16.6.1
Weezify 1.9.0 (171)

Safari browser
Web app (small screen) 1.9.0 (171)



![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/5c53989b-a2ed-4f59-b653-a692fded2a6d)
