### ISSUE TITLE
Liked songs and new releases lead to "page not available"

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#42]
**Describe the bug**
When I click on either Liked songs or new releases - I receive a "page not available" screen

**To Reproduce**

1. Weezify opens to "your library"
2. Click on "liked songs"
3. See error
4. Return to library
5. Click on "new releases"
6. See error

**Expected behavior**
Clicking on a playlist should open desired playlist

**Screenshots**
https://github.com/riverscuomo/public-bug-hunt/assets/144278926/0c092982-74bf-4411-adc2-8d21b91fcf77

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2nd gen
 - OS: ios 16.6.1
 - Version: iOS app 1.9.0 (170)

**Additional context**
None

**Comment by KCreek1** [comment]
Just went to web app and tried. Same result. 

- iPhone SE 2nd gen
- ios 16.6.1
- safari

Also:

-windows
-google chrome
- web app 1.9.0 (170)

**Comment by SlightlyCompletely** [comment]
Issue occurs on iPad Air 5th gen (running iPadOS 16.6.1) in Weezify v1.9.0 (170).

**Comment by KCreek1** [comment]
Still an issue on 1.9.0 (171) 

iPhone SE 2nd gen
iOS 16.6.1
iOS app 
Safari browser

**Comment by Mel01000001** [comment]
This is now an issue with Android as described above 1.9.0 (173)

Samsung Galaxy S23+
Android Version 13

**Comment by KCreek1** [comment]
Still issue on iOS app 1.9.0 (174)

iPhone SE (2nd gen)
iOS 17.0.1
Weezify iOS app 1.9.0 (174)

**Comment by SlightlyCompletely** [comment]
Also still occurs in Weezify app 1.9.0 174 on iPad Air running iPadOS 17.0.1.

**Comment by The-King-Tom** [comment]
Updated to Android 1.9.1 (build 175), still seeing Page Not Available for New Releases and Liked Songs playlists.

**Comment by SlightlyCompletely** [comment]
Still occurs in Weezify 1.9.2 (176) on iPad Air 5th gen (running iPadOS 17.0.1) but has the differencenoted in this build: the new releases playlist is gone and replaced by “empty playlist”.

**Comment by riverscuomo** [comment]
loadUser
favoriteTrackIdsForThisUser is coming back empty
so likeplaylist is empty

and this is coming up null
var newReleasesPlaylist = allPlaylists.firstWhereOrNull(
        (element) => element.id == constants.newReleasesPlaylistId);
    if (newReleasesPlaylist == null) {
      newReleasesPlaylist = Playlist.empty.copyWith(name: 'New Releases');
    }

**Comment by riverscuomo** [comment]
newReleasesPlaylist 
becasue the score is 0 in firestore, it's not returned in fetch so I was just providing an empty playlist. but ithad not id. so badplaylistid passed.

**Comment by riverscuomo** [comment]
working on small web now.

**Comment by KCreek1** [comment]
Also working on desktop now.

**Comment by KCreek1** [comment]
The new release playlist can be seen but the playlist name is blank on large screen and says "null" on small screen web.

**Comment by SlightlyCompletely** [comment]
Resolved on iPad with Weezify 1.10.0 (179).

**Comment by KCreek1** [comment]
Working on iPhone as well.

**Comment by KCreek1** [comment]
Still working on iOS app 185 (1.11.0)

**Comment by KCreek1** [comment]
Looking at tester spreadsheet - it seems this issue has been resolved since android build 177 and iOS build 179. Going to mark as closed.
