### ISSUE TITLE
Seekbar works for tap but not slide on iPad

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#43]
**Issue**
The seekbar is too low to slide on iPad. Tapping on seekbar still works.

**To Reproduce**
1. While playing a track, try to slide seekbar. 
2. Note that this initiates app switching.
3. Tap a location on seekbar.
4. Note that tapping seekbar will work and move to the appropriate position in the track.

**Expected behavior**
It should be possible to slide the seekbar to find a location in the track.

**Device Information**
 - iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify 1.9.0 (170)

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/ed7249c5-b1c7-4adc-8b41-bc721c0594e7

**Comment by SlightlyCompletely** [comment]
Issue also occurs in web version of Weezify on iPad.

**Device:**
 - iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Browser: Safari
 - Weezify v1.9.0 (web)

**Comment by SlightlyCompletely** [comment]
Issue remains in Weezify 1.9.0 (171) on iPad Air 5th gen running iPadOS 16.6.1.

**Comment by KCreek1** [comment]
I was able to use seekbar by dragging with finger. 

iPad 7th gen
iPadOS 17.0.1
Weezify ios 1.9.2 (176)

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/ebeb1bb0-2f0c-4345-aa01-e1de3b8a4e02
