### ISSUE TITLE
No Logout option

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#45]
**Issue**
There is no longer an option to log out of the app on the Profile screen or anywhere in the app.

**To Reproduce**
1. Tap avatar to get to Profile.
2. Note lack of Logout icon.
3. Tap home.
4. Note no Logout icon there either.

**Expected behavior**
A Logout option should appear somewhere in the app.

**Device**
 - iPad Air 5th gen
 - iPadOS 16.6.1
 - Weezify v1.9.0 (170)

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/27773436-89d4-43ca-8cc6-688cc19a06f2

**Comment by KCreek1** [comment]
It also does not appear on the web app.

Windows 
Chrome
Web app 1.9.0 (170)

**Comment by KCreek1** [comment]
Fixed in 1.9.0 (171)

**Comment by riverscuomo** [comment]
now i had to make sure screen was set to 'user' in shellappbar
