### ISSUE TITLE
Audio not playing on web Weezify

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#46]
**The Issue**
Audio does not play except for sonata playlist, and these only play if no other playlist was attempted before them.

**To Reproduce**
1. Open web version of Weezify.
2. Begin playing default sonata playlist.
3. Note that audio seems fine, then pause playback.
4. Select another playlist and double-tap to begin playback.
5. Note there is no audio, then pause playback.
6. Select sonata playlist again and double-tap to start playback.
7. Note there is no audio now.

**Expected behavior**
All tracks should have audio.

**Device:**
 - iPad Air 5th gen
 - OS: 16.6.1
 - Browser: Safari
 - Weezify 1.9.0 (170)

**Additional note **
Issue also occurs in this web version of Weezify on iPhone 7 (running iOS 15.7.9) using Safari.

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/205bef51-10c9-456b-ba65-944960258ee7

**Comment by SlightlyCompletely** [comment]
Issue remains in web Weezify 1.9.0 (171) on devices mentioned above.

**Comment by SlightlyCompletely** [comment]
Update: the issue, confirmed by @KCreek1 and @Minority103, was double-tapping a song to start. If the blue play button is used to start playback, tracks will play fine. If double-tap is used to start playback, there’s no audio even though the track appears to be playing.

**Comment by KCreek1** [comment]
I put this video in discord but I'll upload it here too. 

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/a4d4fe25-6d87-4445-ac8f-c14bf0c00685

**Comment by SlightlyCompletely** [comment]
Resolved by updating to iOS/iPadOS 17.
