### ISSUE TITLE
Search neighbors button not functioning

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#48]
**The Issue**
Unlike the iPhone version, the top bar in Weezify on iPad doesn’t show “Good Evening”, search icon, or the plus icon for creating new playlists.

**To Reproduce**
1. Open Weezify or navigate to Home screen.
2. Note issue.

**Expected behavior**
The top bar (or other location) should display “Good Evening”, the search icon, and the plus icon just as the iPhone version does.

**Device:**
 - iPad Air 5th gen
 - OS: iPadOS 16.6.1
 - Weezify v1.9.0 (171)

Screenshots show iPad version compared to iPhone 7 (running iOS 15.7.9) version.

![IMG_2419](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/2906d935-e133-4a9d-a972-e13ca044d751)
![IMG_8260](https://github.com/riverscuomo/public-bug-hunt/assets/144279871/bd34f80f-234d-4b67-92fd-102b52452bdf)

**Comment by SlightlyCompletely** [comment]
Issue partially remains in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1. The app now says good morning/afternoon but magnifying glass, while sometimes present, doesn’t work properly (this is reported in another issue). No playlist create button exists at the top, but this may have been removed in this latest version of Weezify.

**Comment by SlightlyCompletely** [comment]
Also occurs in Weezify v1.9.2 (176) on iPad Air running iPadOS 17.0.1, with greeting issue resolved but magnifying glass sometimes disappearing. (It seems that going to profile then to home will bring back the search icon, but it still doesn’t work (as issue 38). While there is a playlist create or add (plus) button on the lefthand menu, neither it nor the Library button next to it works.

**Comment by KCreek1** [comment]
I was able to use the create playlist by tapping on create playlist button on my iPad this morning. 

iPad 7th gen
iPadOS 17.0.1
Weezify iOS app 1.9.2 (176)

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/5ab944d4-d728-46cd-b513-79059ac4ccf4

**Comment by KCreek1** [comment]
https://github.com/riverscuomo/public-bug-hunt/issues/38#issuecomment-1740105702

I have some observations regarding the search button on iPad that I put in issue #38 (link above).

After looking at desktop web: I also wonder if the Library tab (although it turns a little grey when tapped) is actually a header for the Library underneath and not a button to be used.  Possibly the grey is residual from the create playlist button.

**Comment by KCreek1** [comment]
All other aspects of this issue are resolved.

iPad app and iPad web have a "search neighbors" button on the profile page that is not functioning however. 

iPad 7th gen
IPadOS 17.0.1
iOS app 1.9.2 (177)

**Comment by SlightlyCompletely** [comment]
Regarding the Search option at the top of Profile, the only remaining part of this issue unresolved: 

Tapping the magnifying glass at the top of the Profile section leads to “Page Not Found” as shown in video below. It should search users/neighbors.

Issue occurred in Weezify 1.9.2 (177) on the following devices (in addition to KCreek’s directly above):

- iPad Air (5th gen) running iPadOS 17.0.2
- iPad (regular, 5th gen) running iPadOS 16.7


https://github.com/riverscuomo/public-bug-hunt/assets/144279871/ecbfe665-7edc-4da1-b8ce-eb30d9679edc

**Comment by KCreek1** [comment]
This is also issue on web app on desktop.

windows
Chrome browser

**Comment by KCreek1** [comment]
Working on tablet web now.

**Comment by KCreek1** [comment]
Working on iPad 
iOS app 1.10.0 (179)
