### ISSUE TITLE
Player control bar - time display

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#5]
**Describe the bug**
The player control bar cuts off the time played and time remaining.

**To Reproduce**
1. Select song to play. 
2. Click on player control bar for full song information screen.  
3. Notice song times are cut off. 

**Expected behavior**
Typically you can see the time played/remaining. 

**Screenshots**
![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/67e64732-ffba-4348-a4b7-6daa9322539a)

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2nd gen)
 - OS: iOS 16.6 
 - Version Weezify iOS app 1.8.6 (153)

**Additional context**
None

**Comment by SlightlyCompletely** [comment]
This issue in Weezify iOS app 1.8.6 (153) also occurs on iPhone 7 running iOS 15.7.8, with lefthand time marker displaying only seconds and righthand time marker displaying what appears to be minutes.

**Comment by Minority103** [comment]
This is an issue too on iPhone 14 pro running iOS 16.6 and weezify app 1.8.6 (153).

**Comment by KCreek1** [comment]
Fixed on iPhone SE (2nd gen) running iOS 16.6.1 and Weezify 1.8.9 (168)

**Comment by SlightlyCompletely** [comment]
Resolved on my iPhone 7 (iOS 15.7.8) as well, by updating to Weezify v1.8.9.
