### ISSUE TITLE
“No account? Sign up” unresponsive after logging out

### ISSUE THREAD

**Issue by slobulike** [riverscuomo/public-bug-hunt#59]
**Describe the bug**
After logging out of the app, the log in page is displayed but the “No account? Sign up” button is unresponsive. “Sign in with Google” and “Maybe later” both work as expected.

**To Reproduce**
1. Go to Profile page and log out
2. Click on “No account? Sign up”
3. Nothing happens

**Expected behavior**
Sign up screen is displayed 

** Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android
 - Browser - App
 - Version 1.9.0 (24th Sept)

**Additional context**
I don’t think this likely to be causing too many issues for real users as the same behaviour doesn’t occur when using the “No account? Sign up” from the lurker profile page which is how new users should arrive at the Sign Up screen.

**Comment by KCreek1** [comment]
Issue on iPhone as well. 

iPhone SE (2nd gen)
iOS 17.0.2
iOS app 1.9.2 (177)

**Comment by urbainn** [comment]
Seems to have been resolved for 1.10.1 (180) on android

**Comment by slobulike** [comment]
Yes, agree. Worked when creating a new account from that screen on 180.

**Comment by slobulike** [comment]
Re introduced on v183 (1.10.2)

**Comment by KCreek1** [comment]
I was able to sign up on iOS app 185 (1.11.0)
