### ISSUE TITLE
Grey screen displayed when selecting New Releases playlist

### ISSUE THREAD

**Issue by slobulike** [riverscuomo/public-bug-hunt#6]
**Describe the bug**
After selecting the New Releases playlist on the Player screen, the main screen goes grey. The nav bar and play bar still show correctly.

**To Reproduce**
1. Go to 'Player tab'
2. Click on 'New Releases'
3. Grey screen shown

**Expected behavior**
New releases playlist (even if empty) should be displayed

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 13
 - Browser: Android app
 - Version: 1.8.7 (165)

**Additional context**
Some users experience the same issue when selecting the Liked Songs playlist

**Comment by KCreek1** [comment]
After reading this I have noticed the same issue on iOS app:

iPhone SE (2nd gen)
iOS 16.6
Weezify iOS app 1.8.6 (153)

**Comment by KCreek1** [comment]
This is also an issue on iPhone SE (2nd gen) running iOS 16.6 and weezify app 1.8.6 (153)

**Comment by SlightlyCompletely** [comment]
This issue also occurs (with both New Releases and Liked Songs) on iPad Air 5th gen running iPadOS 16.6 and iPhone 7 running 15.7.8 (Weezify iOS app v. 1.8.6 on both devices).
