### ISSUE TITLE
App version not displayed on Profile screen

### ISSUE THREAD

**Issue by slobulike** [riverscuomo/public-bug-hunt#60]
**Describe the bug**
The app version is no longer displayed on the Profile page.

**To Reproduce**
1. Go to 'Profile' screen
2. Look at bottom of screen for version details
3. Unable to see version details 

**Expected behavior**
The version details should be displayed as Weezify 1.x.x (xx)

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android
 - App
 - Version 1.9.0

**Additional context**
The play store only shows the main version number e.g. 1.9.0 so it’s not possible to confirm the specific release e.g. 174

**Comment by KCreek1** [comment]
Confirmed in iOS app. No version number on profile. Only main 1.9.0 in App Store. 

iPhone SE (2nd gen)
iOS 17.0.1
Weezify iOS app 1.9.0 (174)

**Comment by SlightlyCompletely** [comment]
Also occurs in Weezify app 1.9.0 174 on iPad Air running iPadOS 17.0.1.

**Comment by KCreek1** [comment]
It's visible in iOS app 1.9.2 (176)

iPhone SE (2nd gen)
iOS 17.0.1

**Comment by slobulike** [comment]
Fixed in Android 1.9.2 (176)
