### ISSUE TITLE
Profile text runs out of bounds of screen

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#62]
**Describe the bug**
When you click on an artist to see their profile - their name and profile run off the edge of the screen. 

**To Reproduce**

1. Go to "Best of By the People" playlist
2. Click on an artist's name
3. Notice in profile that name is to the right of screen center and profile text runs off right edge of screen. 

**Expected behavior**
You should be able to read the full profile. 

**Screenshots**
![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/5d3c4515-ff3c-40fa-83f6-382ca1207806)

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/eb45506f-078a-4f9d-b11c-9c4c65daa46e)

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2nd gen)
 - OS: iOS 17.0.1
 - Version: 1.9.0 (174)

**Additional context**
None

**Comment by SlightlyCompletely** [comment]
Issue also occurs in Weezify 1.9.0 (174) on iPad Air running iPadOS 17.0.1. It happens on my own profile as well.

**Comment by riverscuomo** [comment]
1.10.0

**Comment by KCreek1** [comment]
Can see the full text in 1.10.0
