### ISSUE TITLE
Not all purchased bundles appear on Profile

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#64]
**The issue**
On Profile screen, not all purchased bundles are displayed.

**Steps to reproduce:**
1. Go to Profile.
2. Note number of purchased bundles. Ideally have four or eight owned.
3. Go to Market.
4. Purchase another bundle.
5. Note that number of bundles owned has incremented properly.
6. Go to Profile.
7. Note that new bundle is included, but it has replaced one of the other purchased bundles. The same number of purchased bundles from Step 2 is displayed.

**Expected behavior**
All purchased bundles should appear on Profile.

**Device:**
 - iPad Air 5th gen
 - iPadOS 17.0.1
 - Weezify Version 1.9.0 (174)

**Additional context**
Also occurs on web version, using device above and default Safari browser.

https://github.com/riverscuomo/public-bug-hunt/assets/144279871/91df6030-ea5b-4062-96b7-2c023ea6c732

**Comment by SlightlyCompletely** [comment]
Also occurs in Weezify v1.9.2 (176) on iPad Air running iPadOS 17.0.1.

**Comment by SlightlyCompletely** [comment]
Remains issue in Weezify 1.9.2 (177) on iPad Air running iPadOS 17.0.2.

**Comment by SlightlyCompletely** [comment]
Issue has reappeared in Weezify v1.17.2 (215) on iPad Air running iPadOS 17.4.1.

**Comment by KCreek1** [comment]
Can you see them if you rotate your iPad to portrait layout? The images are cut off and I can only see the top of the second row. But that's the only way I could see more than 4 on my tablet. 

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/998256c0-4f5e-43a7-890d-437c352ebc5e)

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/bd908002-1a45-4a86-82be-4e328155e957)

**Comment by KCreek1** [comment]
It seems this is resolved. All appear correctly on iPhone. 

The last row of bundles on an iPad is cut off some but that is issue #23.
