### ISSUE TITLE
Double click on profile crashes the app

### ISSUE THREAD

**Issue by urbainn** [riverscuomo/public-bug-hunt#67]
**Describe the bug**
Double-clicking on the round profile button in the upper right, or clicking it multiple times (not necessarily in a short timespan) will crash the app/display a grey screen on most of the page, which I can't seem to remove unless I refresh the URL. It only works when I haven't loaded/clicked on any playlist, the moment I go to a playlist, the bug is completely resolved, even if I go back to the welcome page or the profile.

**To Reproduce**
1. Reload the page.
2. Go to any page (except a playlist).
3. Click multiple times on your profile icon.
4. App should crash.

**Expected behavior**
I would expect the profile page to be displayed.

**Screenshots**
If applicable, add screenshots to help explain your problem. These are very helpful!

![dldldlsdlsdlssdfssdfsdfsdfsbgsddeLA PIERRREdddddddLAghghgh DEFENSEdmosdWEEZIFYfsLA MINEdfdcemo](https://github.com/riverscuomo/public-bug-hunt/assets/47057465/beeeb724-53fe-4eea-a74b-530c162104c2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 117.0.5938.132 

**Smartphone (please complete the following information):**
N/A

**Comment by KCreek1** [comment]
I think this may now be fixed.
