### ISSUE TITLE
All songs display 5 star rating on ios small web

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#69]
**Describe the bug**
On web app - all songs display 5 star rating despite never being rated or rated differently. 

**To Reproduce**

1. Select playlist
2. Click on any song
3. Notice displays 5 star rating
4. Click on stars
5. Notice no change in rating

**Expected behavior**

Songs not previously rated should display no stars. Previously rated songs should show correct number of stars. Tapping on stars should change display. 

**Screenshots**
https://github.com/riverscuomo/public-bug-hunt/assets/144278926/a7f7d3b0-1601-46f7-8922-4bcc88af01d5

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2nd gen)
 - OS: iOS 17.0.3
 - Browser: Safari
 - Version: web app 1.10.0 (177)

**Tablet**
 - iPad 7th gen
 - iPadOS 17.0.3
 - Browser: safari
 - Version: web app 1.10.0 (177)

**Additional context**
None

**Comment by riverscuomo** [comment]
I'm not able to reproduce this bug on chrome.

**Comment by KCreek1** [comment]
I can't reproduce on chrome either.  Possibly iOS web specific then.

**Comment by riverscuomo** [comment]
@KCreek1 still an issue?

**Comment by KCreek1** [comment]
@riverscuomo Yes. On small web app the player bar still shows 5 stars regardless of the actual rating. Both on mobile and tablet.

**Comment by KCreek1** [comment]
Just took a look at this - the ratings are now correct on small web on both phone and tablet.
