### ISSUE TITLE
Search results for songs show + not three dots

### ISSUE THREAD

**Issue by slobulike** [riverscuomo/public-bug-hunt#75]
**Describe the bug**
The test sheet suggests that song search results should display the three dots that are shown in other areas e.g. when browsing a playlist, instead a plus (+) symbol is shown.

**To Reproduce**
1. Go to 'song search'
2. Enter some text that returns results e.g. st george
3. See error

**Expected behavior**
The three dots should be displayed next to each song on the search results list.

**Screenshots**
![Screenshot_20231020-211809](https://github.com/riverscuomo/public-bug-hunt/assets/48949712/ab824b7d-7a75-4f8a-9c31-d0512b66cfd2)

Example of three dots shown next to track on playlist view.

![Screenshot_20231020-213205](https://github.com/riverscuomo/public-bug-hunt/assets/48949712/1492af65-9740-4b81-bb49-fa5f13381b5f)

**Smartphone (please complete the following information):**
 - Device: [ Pixel 6a]
 - OS: [Android 14]
 - Browser [Chrome and App]
 - Version [v1.10.0 (177)]

**Additional context**

**Comment by KCreek1** [comment]
In iOS v185 (1.11.0) the 3 dots appear as they should. 

![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/cf122469-d738-4081-b0f9-ecd87dd1f1ba)
