### ISSUE TITLE
Bundle description audio still playing when popup is closed

### ISSUE THREAD

**Issue by urbainn** [riverscuomo/public-bug-hunt#76]
**Describe the bug**
On android, when clicking on a bundle in the profile, it opens a popup with track names and plays an audio. When clicking the 'close' button, audio stops, but when closing the popup by clicking on the area around the popup, audio will still play.

**To Reproduce**
1. Go to your profile
2. Click on a bundle in the 'bundles' category
3. Close the popup by clicking on the backdrop/on the area around the popup
4. Bundle description audio should still play

**Expected behavior**
The audio should stop when the popup is closed.

**Smartphone (please complete the following information):**
 - Device: Sony Xperia
 - OS: Android 13
 - Version: 1.10.0 (179)

**Comment by KCreek1** [comment]
See also issue #18

**Comment by urbainn** [comment]
Oops, thought I've searched all issues. I'll close this one.
