### ISSUE TITLE
Link created when sharing a playlist takes you to "Page not found"

### ISSUE THREAD

**Issue by slobulike** [riverscuomo/public-bug-hunt#8]
**Describe the bug**
The link generated when selecting "Copy link to playlist" is invalid and takes you to a page not found screen.

**To Reproduce**
1. Go to 'Player tab'
2. Long click on any playlist 
3. Click on 'Copy link to playlist'
4. Use generated link
5. Page not found message shown

**Expected behavior**
You are taken to the playlist.

**Smartphone (please complete the following information):**
 - Device: [Pixel 6a]
 - OS: Android 13
 - Browser [Android App and Chrome browser]
 - Version 1.8.7(165)

**Additional context**
An example generated URL is https://weezify.web.app/#/nvD0gesKQHaap5k2gbiW (for the Pacific daydream playlist)

If the URL is edited to https://weezify.web.app/#/playlist/nvD0gesKQHaap5k2gbiW (i.e adding in /playlist after /#) the link opens correctly.

**Comment by Mel01000001** [comment]
The link created is now active, but it takes you to a different location then expected.  This was the URL generated for Best of Weezma https://weezify.web.app/#/playlist/CPAfuZxpQQsgJcLRD4Xe

This was the result when following the above link
![Screenshot_20230909_155913_Chrome](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/343a3e93-ddbf-4bda-844f-c6ce98d9f632)

**Comment by KCreek1** [comment]
I had same result as above. Playlist for Patrick and Rivers took me to the same place - New Playlist. 

iPhone SE (2nd gen)
iOS 16.6.1
Weezify 1.8.9 (168)
