### ISSUE TITLE
upload dSYM 

### ISSUE THREAD

**Issue by riverscuomo** [riverscuomo/public-bug-hunt#81]
USER
how do i upload this? what is this?

Crashlytics detected a missing dSYM for version 1.10.1 (182)
dSYM UUID
*****
ASSISTANT
This message indicates that Firebase Crashlytics, a real-time crash reporter, has detected a missing 'dSYM' file for your app's version 1.10.1 (182). A dSYM file (debug symbols file) contains the debug symbols for your app. This file is used to symbolicate crash logs, which attach human-readable function names and line numbers to machine-level memory addresses in a crash stack trace. Without it, Crashlytics won't be able to accurately report crashes for your app.

To upload dSYM file for Firebase Crashlytics, follow these steps:

1. First, locate your dSYM file. It may be in your Xcode archives, or in case of Bitcode-enabled apps, you can download it from the Apple Developer portal.

2. Now, to upload the file, you can use either the Firebase console or the Crashlytics CLI (Command Line Interface). 

  **Console Method**
    a. Go to the Firebase Console.
    b. Select your project.
    c. Go to 'Quality' > 'Crashlytics'.
    d. Go to 'Missing dSYM' tab.
    e. Click 'Add dSYM' and follow the prompts to upload your dSYM file.

  **CLI Method**
    a. Install the Crashlytics CLI, if not done already.
    b. Use the `upload-symbols` command specifying -gsp (path to your GoogleService-Info.plist file), -p (platform, either ios, tvos, or macos), and path to your dSYMs.
    c. An example command can be:
        `./upload-symbols -gsp /path/to/GoogleService-Info.plist -p ios /path/to/dSYMs`
  
3. After the upload, Crashlytics will be able to process any crashes associated with that dSYM and you should start receiving crash reports on your Firebase console.

Remember that for future builds, you might want to automate the dSYM upload process. Firebase provides different ways to do it, based on whether you want to manually upload the dSYM files, automatically upload the dSYM files, or upload the dSYM files only for Bitcode-enabled apps. The best method depends on your project's needs and workflow.

## i don't beleive i have any dysms. how do i create them?
ASSISTANT
If you are developing an iOS app with Xcode, dSYM files are created automatically during the build process if the "Debug Information Format" setting in build settings is set to "DWARF with dSYM File".

Here's how you can ensure that setting is correct:

1. Open your project in Xcode.

2. Choose your Target and go to 'Build Settings'.

3. Look for 'Debug Information Format'.

4. For Debug Configuration, set this to 'DWARF', and for Release Configuration, set it to 'DWARF with dSYM File'.

Now, when you build your project, the dSYM files will be created. You can find them in the Xcode Archive:

1. Go to 'Window' > 'Organizer'.

2. Select your App's archive.

3. Right-click on the archive and choose 'Show in Finder'.

4. Right-click on the xarchive file, and choose 'Show Package Contents'.

5. Inside, you'll see a folder named "dSYMs" which will contain your .dSYM files.

If your app is compiled with Bitcode, which it is by default on Xcode, the dSYM files will be generated and stored by Apple as part of the Bitcode recompilation process. You can download them from the 'Activity' tab in your App Store Connect portal.

For the missing dSYM mentioned in the Crashlytics error message, you'll need the dSYM for the exact version/build of your app (1.10.1 (182) in this case). If this was not a recent build or if you've not kept the Xcode archives, you may not have the exact dSYM files.

**Comment by taylorlee3** [comment]
If you get this email again, you can click on the link and upload it manually from there.

To find the dysm files, follow these steps:
Go to 'Window' > 'Organizer'.

Select your App's archive.

Right-click on the archive and choose 'Show in Finder'.

Right-click on the xarchive file, and choose 'Show Package Contents'.

Inside, you'll see a folder named "dSYMs" which will contain your .dSYM files.
