### ISSUE TITLE
No rating stars available

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/public-bug-hunt#89]
**Describe the bug**
There are no rating stars available on the player bar for any track. 

**To Reproduce**
1. Open app
2. Select track to play
3. Notice player bar is missing rating stars

**Expected behavior**
Once you select an available track to play, there are stars for you to rate the track. 

**Screenshots**
![image](https://github.com/riverscuomo/public-bug-hunt/assets/144278926/e58653b9-c18b-4cfc-a23b-dc18aa708c27)

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2nd gen
 - OS: iOS 17.0.3
 - Version iOS app v186 (1.12.0)

**Additional context**
None

**Comment by riverscuomo** [comment]
I think if you tap on the player it will open a details screen with the rating widget for that track

**Comment by KCreek1** [comment]
> I think if you tap on the player it will open a details screen with the rating widget for that track

When I tap on details the ratings stars are still missing. 

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/28f1d1ca-8975-4c0e-b8a8-9d8373f9c0bb

**Comment by KCreek1** [comment]
They're back.
