### ISSUE TITLE
Buttons Appear Over Song Search Results

### ISSUE THREAD

**Issue by Mel01000001** [riverscuomo/public-bug-hunt#95]
After searching for song with a query, the results appear with Songs, Playlists and Artists buttons over the top.  This does not affect functionality. 

Device: Samsung Galaxy S23+
OS: Android V 14
Weezify: 188 (1.13.0)

![Screenshot_20231130_233441](https://github.com/riverscuomo/public-bug-hunt/assets/144282154/4814095f-52b0-4ad9-a38d-4afdcc09f11a)

**Comment by KCreek1** [comment]
The top search result seems to be obscured by the search bar.  

iOS 17.3
Weezify iOS 205 (1.15.0)

https://github.com/riverscuomo/public-bug-hunt/assets/144278926/4f59a7cc-4b02-4380-ae43-6bbc3aaf20d8

**Comment by KCreek1** [comment]
All tracks in a search result are visible on iPhone is weezify 215 (1.17.2)
