### ISSUE TITLE
Double tap on previous track button only sporadically works

### ISSUE THREAD

**Issue by SlightlyCompletely** [riverscuomo/public-bug-hunt#96]
**The Bug**
When playing a track, tapping twice on the back arrow/previous track button will occasionally work and occasionally doesn’t have any effect at all.

**To Reproduce**
1. Allow a couple tracks to play
2. Tap twice on previous track button.
3. Note whether it works or not.
4. Repeat from step 1.
5. Note that sometimes this double tap will return to the previous track and sometimes it has no effect.

**Expected behavior**
Double tap on the “previous track” button should consistently start playing the previously played track.

**Device:**
 - iPad Air 5th gen
 - OS: iPadOS 17.1.1
 - Weezify 1.13.0 (188)

**Additional context**
This issue occurred on both newly created and old accounts. The issue persisted with logouts/hard app closes/re-logins and also remained when switching between accounts. Double tap outcome was always unpredictable.

**Comment by KCreek1** [comment]
Seems to be functioning normally on iPhone and iPad on v192 (13.1.1)
