### ISSUE TITLE
Your Library page shows the user info from the previous user

### ISSUE THREAD

**Issue by slobulike** [riverscuomo/public-bug-hunt#97]
When switching between users the previous users data is presented on the Your Library page (see comment on issue 82).

If the newly logged in user purchases a bundle, the Your Library page reloads to show the correct data for the currently logged in user but the new purchase isn't playable.

If an additional bundle is purchased then the Your Library updates to give access to the previously purchased bundle but not the latest purchase.

**To Reproduce**
1. Log in with any user
2. Log out and log in with a different user 
3. Browse to Your Library 
4. See previous users name and bundles can be played
5. Make a purchase from the market
6. Browse to Your Library
7. See current users data
8. Try to play purchased bundle
9. Message advising to purchase bundle is shown
10. Make a purchase from the market
11. Browse to Your Library
12. See current users data
13. Play previously purchased bundle successfully
14. Try to play new purchase
15. Message advising to purchase bundle is shown

**Expected behavior**
The current users data and all purchased bundles are available to play in Your Library.

**Smartphone (please complete the following information):**
 - Device: [Pixel 6a]
 - OS: [Android 14]
 - Browser [Android appi
 - Version [1.13.1 189]

**Comment by KCreek1** [comment]
I had opened this as a new issue but it seems these are the same. 

Describe the bug
When switching between accounts, if I purchase a bundle with one then switch to a new account the bundles in the new account show as unplayable.

To Reproduce
Steps to reproduce the behavior:

1. logon in 1st account
2. purchase bundle
3. confirm it appears in profile and can play and is gone from market
4. log out of 1st account
5. logon to 2nd account
6. purchase bundle
7. confirm it appears in profile and can play and is gone from market
8. log out of 2nd account
9. logon to 1st account
10. notice previously purchased bundles will not play although appearing in profile and gone from market
11. rectified if new bundle is purchased and app closed and reopened but continues in a loop between accts.
12. Fully rectified by deleting one of the new accounts. Using clear cache button. Closing app. Reopening. Bundles playable.



Smartphone (please complete the following information):

Device: iPhone SE (2nd gen)
OS: iOS 17.1.2
Version 190(13.1.1)
Additional context
N/A

**Comment by KCreek1** [comment]
Purchased bundles are playing correctly in the corresponding accounts with build 192 (13.1.1) on iPhone and iPad.

**Comment by Mel01000001** [comment]
Previous issue of seeing previous users' profile/data fixed with Android build 191 (13.1.1), but was unable to log out. Rectified by closing and reopening app.
