### ISSUE TITLE
Song display not updating when using skip, previous and shuffle functions

### ISSUE THREAD

**Issue by Mel01000001** [riverscuomo/public-bug-hunt#99]
The song display on 'Playing From' window, the bar at the bottom of the screen and the song that is highlighted in blue in playlist are not updating when using skip, previous and shuffle functions.

**To Reproduce**
1. Click on any playlist.
2. Click on blue play button or any song.
3. Use skip, previous or shuffle functions to change song being played.

**Expected behavior**
When using skip, previous and shuffle functions, the name of song being played will display on 'Playing From' window, the bar at the bottom of the screen and the song will be highlighted in blue in the playlist. 

**Screenshots**

https://github.com/riverscuomo/public-bug-hunt/assets/144282154/d0b08cac-eeef-4bb5-b7ef-5e69058bf169

**Smartphone**
 - Device: [Samsung Galaxy S23+]
 - OS: [Android v 14]
 - Version [build 191 (1.13.1)]

**Comment by KCreek1** [comment]
This is also an issue on iPhone and iPad. 

iPhone SE (2nd gen)
iOS 17.1.2
iPad 7th gen
iPadOS 17.1.2
Weezify iOS v192 (13.1.1)

**Comment by riverscuomo** [comment]
This was still UserBloc so I changed to PlayerBloc

```dart
class _PlayerSmallTrackDetailScreenState<Track>
    extends State<PlayerSmallTrackDetailScreen> {
  @override
  Widget build(BuildContext context) {
    return BlocBuilder<PlayerBloc, MyPlayerState>(
```

And I had to emit loading and loaded states in PlayerBloc events regarding player controls

**Comment by KCreek1** [comment]
Working correctly in iphone on v193.
